### ISSUE TITLE
zIndex好像不起作用

### ISSUE THREAD

**Issue by weiwill** [ElemeFE/vue-amap#101]
`this.markers.push({
          selected: true,
          draggable: true,
          position: [lnglat.lng, lnglat.lat], 
          icon: require('./../../assets/position-picker.png'), 
          zIndex: 101,
        });`
如上代码，zIndex不起作用
通过谷歌浏览器的选择工具，选择div,发现好像还是100

**Comment by AxeMea** [comment]
@weiwill 

你好，模板里有绑 `zIndex` 吗

**Comment by weiwill** [comment]
啊，抱歉，我没想到这块，绑定之后就可以了，打扰了
