### ISSUE TITLE
el-amap-search-box 组件在不传 events 的情况下会有报错

### ISSUE THREAD

**Issue by dengdan99** [ElemeFE/vue-amap#103]
el-amap-search-box 组件在不传 events 的情况下会有报错

原因：
vue2.0 后不能修改props
https://github.com/ElemeFE/vue-amap/blob/dev/src/lib/components/amap-search-box.vue#L106

项目重时间紧 空了PR

**Comment by MrSuperJ** [comment]
你好， 我也遇到了关于searchbox的问题  请问你是怎么修改呢？

**Comment by 617450941** [comment]
怎么解决 这个bug

**Comment by jerry-i** [comment]
@617450941 最新的修了
