### ISSUE TITLE
如何在events事件中修改其他变量？

### ISSUE THREAD

**Issue by shuaizi96** [ElemeFE/vue-amap#105]
//点坐标数据
        markers: [
        {
          position: [121.5273285, 31.21515044],
          visible: true,
          events: {
            click: () => {
              //将windows[0].visible更改为"true"
            }
          }
        }
      ],

      //信息窗体数据
       windows: [
        {
          position: [121.5273285, 31.21515044],
          content: "123",
          visible: false,
          events: {
            open() {
              //markers[0].visible更改为"false"
            }
            close(){
              //markers[0].visible更改为"true"
            }
          }
        }
      ],

**Comment by AxeMea** [comment]
@shuaizi96 

你好，是要类似这样吗

```
export default {
  data() {
    let self = this;
    return {
      visible: false,
      events: {
        open() {
          self.visible = true;
        }
      }
    };
  }
}
```

**Comment by shuaizi96** [comment]
@AxeMea 
谢谢^_^，就是这个，麻烦您了！
