### ISSUE TITLE
如何在自己的应用中实现自由的拾取高德地图坐标？

### ISSUE THREAD

**Issue by dingyiming** [ElemeFE/vue-amap#108]
1、 如何在自己的应用中实现自由的拾取高德地图坐标？即实现高德地图坐标拾取工具，只是放在自己的应用中直接用，
2、 marker如何初始化为当前所定位的位置？

**Comment by AxeMea** [comment]
@dingyiming 

你好。文档进行了升级。

https://elemefe.github.io/vue-amap/#/zh-cn/examples/base/amap

看这里是否能帮助到你
