### ISSUE TITLE
Polyline 不支持 lineJoin 属性

### ISSUE THREAD

**Issue by vvtommy** [ElemeFE/vue-amap#111]

**Comment by AxeMea** [comment]
@vvtommy 

你好，文档里面漏掉了，实际上应该是支持的。你可以尝试下。

**Comment by vvtommy** [comment]
https://github.com/ElemeFE/vue-amap/blob/dev/src/lib/components/amap-polyline.vue#L9
好像并不支持。

**Comment by AxeMea** [comment]
@vvtommy 

看来真的漏了，尴尬。 = =

**Comment by AxeMea** [comment]
@vvtommy 

如果现在急需的话，可以通过 `init`

```
{
  events: {
    init(o) {
      o. setOptions(lineJoin, '');
    }
   }
}
```

**Comment by HengCC** [comment]
好像还是不行啊,是我使用错误码?

```
 <el-amap-polyline :path="currentPolylinePath" strokeStyle="dashed" lineJoin="round" />
```
效果依旧是尖角

**Comment by xuejiangjun** [comment]
> 好像还是不行啊,是我使用错误码?
> 
> ```
>  <el-amap-polyline :path="currentPolylinePath" strokeStyle="dashed" lineJoin="round" />
> ```
> 效果依旧是尖角

stroke-style="dashed" line-join="round"
