### ISSUE TITLE
信息窗体BUG

### ISSUE THREAD

**Issue by Shao-xiaohhua** [ElemeFE/vue-amap#112]
信息窗体打不开 提示position undefined

**Comment by AxeMea** [comment]
@Shao-xiaohhua 

你是不是没有绑 `position`

**Comment by Shao-xiaohhua** [comment]
怎么绑呢 一开始还能用 好像是高德更新了 你们文档里面的信息窗体也不能用了 你检查一下 visible的问题

**Comment by AxeMea** [comment]
@Shao-xiaohhua 

你好，可以更新下 `vue-amap`

参考链接：
https://elemefe.github.io/vue-amap/#/zh-cn/examples/windows/info-window

**Comment by Shao-xiaohhua** [comment]
谢谢
