### ISSUE TITLE
信息窗口出现bug

### ISSUE THREAD

**Issue by yanrome** [ElemeFE/vue-amap#116]
添加一个marker  <el-amap-marker> 再添加一个<el-amap-info-window>,就出现'position' of undefined"，如果两个单独使用没有问题，对了，使用的是你刚刚更新过的

**Comment by AxeMea** [comment]
@yanrome 

我觉得可能是你代码的问题，能贴下代码吗？

**Comment by yanrome** [comment]
我copy你的那个示例里面的代码单独写了一个文件好像还是不行，
<template>
  <div class="amap-page-container">
    <el-amap
      vid="amapDemo"
      :center="center"
      :zoom="zoom"
      class="amap-demo">
      <el-amap-marker v-for="marker in markers" :position="marker.position" :events="marker.events"></el-amap-marker>
      <el-amap-info-window v-for="window in windows" :position="window.position" :visible="window.visible" :content="window.content"></el-amap-info-window>
    </el-amap>
  </div>
</template>
或许是配置没有配好吧，webpack.config.js里面是必须配置的吗？最初我配好了main.js里面发现能引用地图就没有继续管了

**Comment by AxeMea** [comment]
@yanrome 

如果地图组件能够出来，那么其他组件也应该已经正常引入了。

你出现的问题，应该是和你的逻辑代码有关。

**Comment by yanrome** [comment]
已经解决了，多谢大佬
