### ISSUE TITLE
在地图未初始化的时候运行设置center的代码

### ISSUE THREAD

**Issue by yeahTibbers** [ElemeFE/vue-amap#119]
![tim 20170526163534](https://cloud.githubusercontent.com/assets/10751521/26487306/8b77143c-4231-11e7-894d-441a75007bdf.png)

**Comment by AxeMea** [comment]
@yeahTibbers 

为啥要这么干

**Comment by yeahTibbers** [comment]
可是我是根据demo里的代码来的呀
根据文档和demo，我理解的是，当加载el-amap组件后，开始调用自定义的方法与事件时，地图应该已经初始化完了，但是实际上不是
下面是我的用法，您看看哪里是有问题的

![tim 20170526200312](https://cloud.githubusercontent.com/assets/10751521/26493923/c1c8d8aa-424e-11e7-84ce-8934b6ff1ad8.png)
![tim 20170526200327](https://cloud.githubusercontent.com/assets/10751521/26493925/c1f8ed42-424e-11e7-9a4f-9965984f6ec5.png)

**Comment by yeahTibbers** [comment]
是有几率发生的，有时候会有问题，有时候又行了，交替出现

**Comment by yeahTibbers** [comment]
我又做了一点测试，总结如下：

1、把el-amap组件的  :center 传参去掉之后出现此报错
![tim 20170526203447](https://cloud.githubusercontent.com/assets/10751521/26494791/0523afcc-4253-11e7-81b5-b39c6a629bfd.png)

2、发现了100%复现问题办法，用chrome内核浏览器，关闭缓存，第一次使用手机或PC模式访问页面（第一次不一定报错），然后切成另一个模式访问，100%报错
![999](https://cloud.githubusercontent.com/assets/10751521/26494919/c47a798c-4253-11e7-9c91-6d96811aa5d0.gif)

**Comment by yeahTibbers** [comment]
代码如下

1、main.js配置
![00](https://cloud.githubusercontent.com/assets/10751521/26495014/3df87e26-4254-11e7-8725-7709a3af3e9b.png)
2、vue文件
![01](https://cloud.githubusercontent.com/assets/10751521/26495028/4a405154-4254-11e7-9015-3f5bd9258231.png)
![02](https://cloud.githubusercontent.com/assets/10751521/26495030/4a6b69b6-4254-11e7-8eb4-1268e8a98150.png)
![03](https://cloud.githubusercontent.com/assets/10751521/26495027/4a3affa6-4254-11e7-9110-6d0483e699f4.png)

**Comment by AxeMea** [comment]
OK，我花点时间看看。

**Comment by zz1992to2010** [comment]
你好，有个问题咨询下：
初始化地图时，除了center坐标外，还有其他方式没？
我现在的需求：初始化地图时用城市名，不用center属性。在有搜索结果之后，又要根据center属性移动地图中心。但是初始化不用center属性时，后面不能根据center移动。
帮忙解答下，谢谢。

**Comment by xiaojian1244** [comment]
你好！我直接使用高德原生sdk，比如let marker = new AMap.Marker会报错，提示Marker is not a constructor，其它引用过的插件Geocoder、PlaceSearch也一样，难道是还需要CDN引入amap js文件？

**Comment by jerry-i** [comment]
如果使用了组件，就在地图的 init 时间里进行操作；如果没用就在 `lazyAMapApiLoaderInstance.load()`这个Promise之后；支持重复调用
