### ISSUE TITLE
引用时组件出现未定义变量，组件传值也有问题

### ISSUE THREAD

**Issue by chenyinhuan** [ElemeFE/vue-amap#122]
引用第一个地图的时候出现Cannot read property '0' of undefined；
引用search组件时：Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "events"

**Comment by jerry-i** [comment]
更新下版本，应该解决了
