### ISSUE TITLE
怎么显示驾车路线

### ISSUE THREAD

**Issue by dumuzhou** [ElemeFE/vue-amap#123]
{
        pName: 'Driving',
        events: {
          init(o) {
              o.search([116.379028, 39.865042], [116.427281, 39.903719], function(status, result) {})
            }
        }
}
添加上面代码后页面没有显示路线

**Comment by jerry-i** [comment]
#138

**Comment by xianfuxing** [comment]
同上，可以打印status, result 但是不显示路径
