### ISSUE TITLE
经纬度转换地址时报 AMap.Geocoder is not a constructor

### ISSUE THREAD

**Issue by ZhouDH1993** [ElemeFE/vue-amap#124]
// main.js
AMap.initAMapApiLoader({
  // 高德的key
  key: '...',
  // 插件集合
  plugin: ['AMap.Autocomplete', 'AMap.Geocoder' ...]
})

// a.vue
var AMap = require('vue-amap')
......
events: {
          click (e) {
            let {lng, lat} = e.lnglat
            _this.lng = lng
            _this.lat = lat
            // 高德sdk
            var geocoder = new AMap.Geocoder({
              redius: 1000,
              extensions: 'all'
            })
            geocoder.getAddress([lng, lat], function (status, result) {
              if (status === 'complete' && result.info === 'OK') {
                if (result && result.regeocode) {
                  _this.address = result.regeocode.formattedAddress
                  _this.$nextTick()
                }
              }
            })
          }

浏览器一直报 AMap.Geocoder is not a constructor

**Comment by leehomeok** [comment]
我也是遇到这个问题，求大大解决

**Comment by ZhouDH1993** [comment]
你用了eslint吗？ 把你使用amap的文件加在.eslintignore里面就行了

**Comment by AxeMea** [comment]
@leehomeok 

* 不要用 `AMap` 作为 `vue-amap` 的导入名，会和高德全局原生的 `AMap` 冲突。
* 将 `AMap` 在 `eslintrc` 里进行配置。

**Comment by AxeMea** [comment]
@leehomeok 

发现文档中也是将 `AMap` 作为导入名的。给你造成的误解，抱歉。已经对相关部分进行了修正。

参考：

https://elemefe.github.io/vue-amap/#/zh-cn/introduction/init
https://elemefe.github.io/vue-amap/#/zh-cn/introduction/compatible

**Comment by leehomeok** [comment]
@AxeMea  thanks  ，通过参考这个
https://elemefe.github.io/vue-amap/#/zh-cn/examples/base/amap
搞定了

**Comment by HF2018** [comment]
@leehomeok 你好  请问是怎么搞定的啊  各种配置都是按照文档来的  就是使用这个https://elemefe.github.io/vue-amap/#/zh-cn/examples/base/amap理里面的
// 这里通过高德 SDK 完成。
          var geocoder = new VueAMap.Geocoder({
            radius: 1000,
            extensions: "all"
          });
这个的时候  就报错了AMap.Geocoder is not a constructor
