### ISSUE TITLE
信息窗体的弹出事件可以传参吗

### ISSUE THREAD

**Issue by ZhouDH1993** [ElemeFE/vue-amap#125]
我现在把后台返回的数据（其中有字段position : [xxxxxx, xxxxxx],还有其他字段，比如name，age等）直接赋值给markers，然后在`<el-amap-marker v-for="marker in markers" :position="marker.position">`，我看文档上`markers`和`window`是通过`for`循环来加的，能不能像`vue`的`click`事件一样，在`marker`的点击事件的时候`<el-amap-marker v-for="marker in markers" :position="marker.position" @click="handleClick(marker)">`把`marker`对象作为参数传给点击事件,然后在`window`的`content`里面，`姓名：{{marker.name}}   年龄：{{marker.age}}` 这样操作

**Comment by AxeMea** [comment]
@ZhouDH1993 

这个应该是不行的，要动态操作 `content` 里的内容的话，可能需要用 `dom` 来操作了。
