### ISSUE TITLE
Geocoder插件引用有问题

### ISSUE THREAD

**Issue by powainiooo** [ElemeFE/vue-amap#126]
按照你的例子，写的是plugin: ['Geocoder']，无效。写plugin: ['AMap.Geocoder']也无效。
然后在代码里手动加载插件
AMap.plugin(['AMap.Geocoder'],function(){})才有用。
下面是初始化代码（main.js里面）：
import AMap from 'vue-amap'

Vue.use(AMap);
AMap.initAMapApiLoader({
    key: '9243fe9769a63a2356eda20b69b2668e',
    plugin: ['AMap.Scale','AMap.ToolBar','Geocoder']
})

是不是我哪写的有问题？还请指教

**Comment by jerry-i** [comment]
可以啊，都试了下O__O "…

**Comment by jerry-i** [comment]
https://jsfiddle.net/cottonme/aye3fdyo/1/
