### ISSUE TITLE
如何在vue-amap上进行出行路线规划

### ISSUE THREAD

**Issue by Raoul1996** [ElemeFE/vue-amap#138]
我尝试在 模仿定位那一部分的代码书写，但是报了 Cannot read property 'appendChild' of null 的错误。
是因为虚拟DOM的原因吗?
请问如何用vue实现出行路线功能，或者说是vue-amap不支持呢？
可能问题有点蠢。。。。
![1](https://user-images.githubusercontent.com/18366474/27044249-7bac11b4-4fcf-11e7-8cac-3ad511904dd8.png)
![2](https://user-images.githubusercontent.com/18366474/27044250-7bef22ce-4fcf-11e7-8aee-e37d7529bb6e.png)
![3](https://user-images.githubusercontent.com/18366474/27044251-7bfd7540-4fcf-11e7-9b7e-2da7b6cad4d6.png)

**Comment by Raoul1996** [comment]
问题已经解决。
在vue-amap的文档中给出了解决方案。
#### 出现问题的原因
1. 没有意识到 `AMap.Driving` 同样和 `AMap.Geocoder` 一样，是可以作为plugin用的。
2. 在vue的实例中，可以通过`amapManager.getMap()` 方法获取到地图对象，也就是插件需要的`map`参数
3. 然后就可以仿照文档中给的[定位](https://elemefe.github.io/vue-amap/#/zh-cn/plugins/geolocation)的那一部分进行开发啦。
#### 参考链接
1. 高德地图开发者文档的[调起高德地图](http://lbs.amap.com/api/javascript-api/guide/function/callapp)部分
2. [在react实现路径规划的方法](https://jsfiddle.net/h4u8mdng/14/)

第一次写issue，如果有什么错误请告诉我一下下，谢谢vue-amap团队啦，开发出这么方便的包。

附部分代码

` let driving = new AMap.Driving({
              policy: AMap.DrivingPolicy.LEAST_TIME,
              map: self.amapManager.getMap()
            })
            console.log(driving)
            driving.search(
              [{keyword: '秦皇岛站'}, {keyword: '东北大学秦皇岛分校'}],
              function (status, result) {
                button.onclick = function () {
                  driving.searchOnAMAP({
                    origin: result.origin,
                    destination: result.destination
                  })
                }
              }
            )`

**Comment by xiaojian1244** [comment]
你好！有个疑问，说明文档和你的例子里，都有类似let XXX = new AMap.XXX....语句，比如Map，Marker，Drinving
我在本地运用这种定义方法会报错，提示XXX is not a constructor，个人理解这个AMap应该是高德原生的，而不是import引入的vue-amap。我在本地improt、use和initAMapApiLoader都已齐全，只要不采用上述这种定义方法都没问题。
所以想问的是，想使用此种高德原生API方法，是不是还有哪儿需要引用文件，或是定义，而不只是兼容原生SDK。因为文档中没有说明，在例子中也看不出来是从哪儿引入的。

**Comment by xianfuxing** [comment]
这个是原生API吧？vue-amap的路径规划api，文档里没有。算了还是用原生吧。文档也不友好。

**Comment by Raoul1996** [comment]
是的，文档中没有的，但是库本身留有了拓展的空间。😄

**Comment by caosbad** [comment]
楼上的两个问题是如何将高德的 SDK 搜索结果关联到当前的 vue-amap 中

可以将 vue-amap 中的 map 实例作为 map 参数传入到 AMap.Driving 的构造函数中，这样就能够在 vue-amap 实例中绘制路线了。

```
const driving = new AMap.Driving({
        // 驾车路线规划策略，AMap.DrivingPolicy.LEAST_TIME是最快捷模式
        policy: AMap.DrivingPolicy.LEAST_TIME,
        map: this.mapManager.getMap() // 在初始化的时候 使用 new VueAMap.AMapManager() 引入
      })
```

**Comment by mubaihesha** [comment]
请问new VueAMap.AMapManager() 怎么引入的？

**Comment by mubaihesha** [comment]
> 楼上的两个问题是如何将高德的 SDK 搜索结果关联到当前的 vue-amap 中
> 
> 可以将 vue-amap 中的 map 实例作为 map 参数传入到 AMap.Driving 的构造函数中，这样就能够在 vue-amap 实例中绘制路线了。
> 
> ```
> const driving = new AMap.Driving({
>         // 驾车路线规划策略，AMap.DrivingPolicy.LEAST_TIME是最快捷模式
>         policy: AMap.DrivingPolicy.LEAST_TIME,
>         map: this.mapManager.getMap() // 在初始化的时候 使用 new VueAMap.AMapManager() 引入
>       })
> ```
请问new VueAMap.AMapManager() 怎么引入的？

**Comment by mubaihesha** [comment]
> 楼上的两个问题是如何将高德的 SDK 搜索结果关联到当前的 vue-amap 中
> 
> 可以将 vue-amap 中的 map 实例作为 map 参数传入到 AMap.Driving 的构造函数中，这样就能够在 vue-amap 实例中绘制路线了。
> 
> ```
> const driving = new AMap.Driving({
>         // 驾车路线规划策略，AMap.DrivingPolicy.LEAST_TIME是最快捷模式
>         policy: AMap.DrivingPolicy.LEAST_TIME,
>         map: this.mapManager.getMap() // 在初始化的时候 使用 new VueAMap.AMapManager() 引入
>       })
> ```

请问new VueAMap.AMapManager() 怎么引入的？
