### ISSUE TITLE
无法引用高德地图原生SDK

### ISSUE THREAD

**Issue by isWill** [ElemeFE/vue-amap#139]
![image](https://user-images.githubusercontent.com/18042440/27022956-f89d66fc-4f82-11e7-925d-e3804e1b4c85.png)
说实话，我一直没看懂这部分的说明，希望作者能够将“兼容高德原生 SDK”这部分再详细说明一下，非常感谢！

**Comment by jerry-i** [comment]
本组件基于高德脚本，所以会自己load一遍。如果用户自己想使用原始的高德API就需要知道什么时候原始脚本load完，在init方法里面运行的脚本肯定在高德脚本load完之后运行的，所以可以使用原生的高德方法
