### ISSUE TITLE
使用city初始化地图以后，没法改变center

### ISSUE THREAD

**Issue by zz1992to2010** [ElemeFE/vue-amap#140]
开始使用city初始化地图，之后搜索内容，搜索完之后，由于拿不到center，所以无法完成移动。

city和center不能同时存在，但是初始化时，center是未知的。

请问有其他办法没？谢谢。

`<el-amap :vid="vid" 
			:zoom="zoom" 
			:map-manager="amapManager" 
			:plugin="plugin" 
			:events="events"
			:city="city">`

**Comment by jerry-i** [comment]
没有city这个属性。原文档也没有http://lbs.amap.com/api/javascript-api/reference/map
建议这样，初始化设一个默认的center，初始化完成后，在init方法里使用搜索公共获取城市中心点，在更新到原来的center

**Comment by zz1992to2010** [comment]
http://lbs.amap.com/api/javascript-api/example/map/set-center-according-to-map-name/

这个特性有集成吗？
