### ISSUE TITLE
是否有了点聚合的功能？

### ISSUE THREAD

**Issue by dmlzj** [ElemeFE/vue-amap#142]
如题，插件有这个功能吗？谢谢！

**Comment by jerry-i** [comment]
不好意思，暂时没有。之前业务中也遇到过，自己通过zoom的变化，computed出展示的marker，

**Comment by AxeMea** [comment]
@dmlzj 

https://elemefe.github.io/vue-amap/#/zh-cn/examples/coverings/marker-cluster
