### ISSUE TITLE
关于兼容高德原生SDK

### ISSUE THREAD

**Issue by xiaojian1244** [ElemeFE/vue-amap#144]
https://elemefe.github.io/vue-amap/#/zh-cn/introduction/compatible
文档中的说明能理解，已实践尝试过，通过init这个event的参数来使用各种方法。
针对所给例子，在init函数内，以及方法add函数中，有let marker = new AMap.Marker....语句
我在本地运用这种定义方法会报错，提示Marker is not a constructor，个人理解这个AMap应该是高德原生的，而不是import引入的vue-amap。在本地improt、use和initAMapApiLoader都已齐全，只要不采用上述这种定义方法都没问题。
所以想问的是，想使用此种高德原生API方法，是不是还有哪儿需要引用文件，或是定义，而不只是兼容原生SDK。因为文档中没有说明，在例子中也看不出来是从哪儿引入的。

**Comment by jerry-i** [comment]
本组件是在原生的脚本上做的一些封装，使得地图开发可以声明式编程，本身是会去加载基本的高德脚本。
`Marker is not a constructor` 的错误是因为在高德脚本未加载好，此时上下文中没有 `AMap.Marker` 构建函数，就执行了marker的构建函数。
本身文档里已经将高德脚本初始化的promise暴露出来了 https://elemefe.github.io/vue-amap/#/zh-cn/introduction/init

**Comment by xiaojian1244** [comment]
![20170621214857](https://user-images.githubusercontent.com/12274034/27387599-bc8427f0-56cb-11e7-9838-28e569625f6b.png)
![20170621214907](https://user-images.githubusercontent.com/12274034/27387609-c3221c5c-56cb-11e7-8bbc-3f7c361828cb.png)

谢谢你的回答。你说的办法其实之前试过，在issue里没有提到，但也是不成功。上面两个截图是我最新尝试后的结果。lazyAMapApiLoaderInstance在main.js或是app.vue中使用，都会报错，实在不懂是什么原因。在issue里翻看别人的提问，很多人的代码截图都有相似代码，大多都是成功，发生错误也没有我这种错误的，所以再次求问。

**Comment by AxeMea** [comment]
@xiaojian1244 

你好，把倒入名换一下，不要用 `AMap` ,会和高德全局的 `new AMap(...)` 冲突。比如换成：

```
import VueAMap from 'vue-amap';
Vue.use(VueAMap);
```

**Comment by xiaojian1244** [comment]
@AxeMea 
这个方法也尝试过，那样会直接报错无法运行，提示new AMap.Map(...) 中的 'AMap' is not defined

**Comment by AxeMea** [comment]
在 `eslintrc` 中配置
```
"globals": {
      "AMap": true
  }
```

**Comment by xiaojian1244** [comment]
@AxeMea 
可以了，万分感谢！

**Comment by xu-Aurora** [comment]
> https://elemefe.github.io/vue-amap/#/zh-cn/introduction/init

大佬，能价格wechat嘛？issue的各种回答我试了都没有起效果，都达到不地址解析经纬，一天了，还是没有搞出来。。。
