### ISSUE TITLE
调用，new AMap.Geocoder 出错。Uncaught TypeError: AMap.Geocoder is not a constructor

### ISSUE THREAD

**Issue by xbuding** [ElemeFE/vue-amap#145]
之前根据`var geocoder = new AMap.Geocoder({
                        radius: 1000,
                        extensions: "all"
                    });` 是可以运行的。今天突然不行了，显示`Uncaught TypeError: AMap.Geocoder is not a constructor` 请问这是什么原因呢，麻烦了。

**Comment by xbuding** [comment]
是我改错地方了，忘记初始化Geocoder。

**Comment by leehomeok** [comment]
我也遇到了这个问题 ，@xbuding   请问你是怎么解决的？

**Comment by xbuding** [comment]
AMap.initAMapApiLoader({
  // 高德的key
  key: 'YOUR_KEY',
  // 插件集合
  plugin: ['Geocoder', 'AMap.Autocomplete', 'AMap.PlaceSearch', 'AMap.Scale', 'AMap.OverView', 'AMap.ToolBar', 'AMap.MapType', 'AMap.PolyEditor', 'AMap.CircleEditor']
});
要加plugin上面初始化 Geocoder这个

**Comment by xbuding** [comment]
@leehomeok 
AMap.initAMapApiLoader({
// 高德的key
key: 'YOUR_KEY',
// 插件集合
plugin: ['Geocoder', 'AMap.Autocomplete', 'AMap.PlaceSearch', 'AMap.Scale', 'AMap.OverView', 'AMap.ToolBar', 'AMap.MapType', 'AMap.PolyEditor', 'AMap.CircleEditor']
});
要加plugin上面初始化 Geocoder这个

**Comment by leehomeok** [comment]
这个AMap.Geocoder 已经加了，我在main.js里面初始化的，
在组件里面 引用的，需要再次初始化吗？

**Comment by leehomeok** [comment]
@xbuding 能否加下您的QQ？

**Comment by AxeMea** [comment]
@xbuding 

https://github.com/ElemeFE/vue-amap/issues/144

你好，可以参考这个链接后面的回复。

**Comment by leehomeok** [comment]
@AxeMea  有关constructor的issue 我都看了，但是还是没有找到解决方案。。。

**Comment by Airlyonce** [comment]
没有eslintrc文件怎么解决这个问题

**Comment by Nankis** [comment]
> 没有eslintrc文件怎么解决这个问题

            let geocoder
            AMap.plugin('AMap.Geocoder',function(){
              geocoder = new AMap.Geocoder({
                radius: 1000,
                extensions: "all"
              })
            })
