### ISSUE TITLE
在使用定位 和 进行地图添加标记的时候，定位有个圈里面没法通过点击进行标记

### ISSUE THREAD

**Issue by dingyiming** [ElemeFE/vue-amap#146]
![image](https://user-images.githubusercontent.com/12537013/27250679-a94ce0bc-5367-11e7-8d2c-f9af56cf1c28.png)
只能在圈外点击得到标记
![image](https://user-images.githubusercontent.com/12537013/27250693-fce68282-5367-11e7-8c53-7c82810eefd1.png)

**Comment by jerry-i** [comment]
圈是circle组件？贴下完整的代码

**Comment by jerry-i** [comment]
circle 上添加下点击事件
http://lbs.amap.com/api/javascript-api/reference/overlay#Circle
