### ISSUE TITLE
搜索结果是否可以自定义？

### ISSUE THREAD

**Issue by SAOSO** [ElemeFE/vue-amap#151]
需要显示更多搜索结果内容，例如地址等信息

**Comment by zz1992to2010** [comment]
地址可以用geocoder通过经纬度拿到，如下：
geocoder.getAddress([lngi ,lati], function(status, result) {
});

**Comment by AxeMea** [comment]
@SAOSO 
你好。

可以结合这个实例：

https://elemefe.github.io/vue-amap/#/zh-cn/examples/base/amap
