### ISSUE TITLE
onSearchResult里重新设置地图zoom值无效

### ISSUE THREAD

**Issue by zz1992to2010** [ElemeFE/vue-amap#152]
如下代码片段，注释掉的行经测试是无效的，必须使用manager重新设置才可以
onSearchResult(pois) {
    this.center = [center.lng, center.lat];
    // this.zoom = 11;
    this.amapManager.getMap().setZoom(11);
}

**Comment by jerry-i** [comment]
初始化的时候要给个zoom值
