### ISSUE TITLE
npm 安装方式下如何使用 AMapManager？

### ISSUE THREAD

**Issue by youjiuzidangge** [ElemeFE/vue-amap#154]
vue2.3，按照官网介绍方式，引入 AMapManager，多次尝试使用不成功？

![image](https://user-images.githubusercontent.com/23353593/27527099-881f77c6-5a7c-11e7-94d0-cbaa5a39377c.png)

![image](https://user-images.githubusercontent.com/23353593/27527116-945ef868-5a7c-11e7-940a-803935bc26de.png)

![image](https://user-images.githubusercontent.com/23353593/27527140-a96f88da-5a7c-11e7-9832-8846dc9c1a06.png)

![image](https://user-images.githubusercontent.com/23353593/27527171-d675ec8e-5a7c-11e7-9931-cbfb77b02f5b.png)

**Comment by AxeMea** [comment]
```
let amapManager = new AMapManager();

{
  amapManager: amapManager
}
```
