### ISSUE TITLE
如何计算两点间的距离？

### ISSUE THREAD

**Issue by dcy** [ElemeFE/vue-amap#161]
你好！
请问vue-amap可以计算两点间的距离么？
类似这个https://lbs.amap.com/api/javascript-api/example/calcutation/calculate-distance-between-two-markers

**Comment by AxeMea** [comment]
@dcy  可以的。

其实也就是你看的这个 demo 的写法，没有啥区别。

**Comment by dcy** [comment]
@AxeMea 是直接用官方的写法，还是用vue-amap的api？

**Comment by AxeMea** [comment]
@dcy 

官方的写法
