### ISSUE TITLE
有多个坐标点，如何让地图自适应缩放到合适的大小

### ISSUE THREAD

**Issue by shanshiliu** [ElemeFE/vue-amap#166]

**Comment by jerry-i** [comment]
自己计算边界吧， init里面用 `setBounds ` 后同步下组件外部的数据

**Comment by xming076** [comment]
complete 事件里调用高德地图的API setFitView。

参考代码片段如下：

<template>
      <el-amap ref="myMap" :vid="'amap'" :events="events">
        <el-amap-marker v-for="pos in myPositions" :position="pos">
        </el-amap-marker>
      </el-amap>
</template>
<script>
export default {
  data () {
    events: {
      complete: () => {
         this.$refs.myMap.$amap.setFitView()
      }
    }
  }
}
</script>

**Comment by xming076** [comment]
complete 事件里调用高德地图的API setFitView。

参考代码片段如下：
&lt;template&gt;
      &lt;el-amap ref="myMap" :vid="'amap'" :events="events"&gt;
        &lt;el-amap-marker v-for="pos in myPositions" :position="pos"&gt;
        &lt;/el-amap-marker&gt;
      &lt;/el-amap&gt;
&lt;/template&gt;
&lt;script&gt;
export default {
  data () {
    events: {
      complete: () =&gt; {
         this.$refs.myMap.$amap.setFitView()
      }
    }
  }
}
&lt;/script&gt;
