### ISSUE TITLE
您好，在使用定位插件时偶尔会遇到 Uncaught (in promise) TypeError: AMap.Map is not a constructor。刷新之后就又可以了，不知道什么原因。代码如下。

### ISSUE THREAD

**Issue by hiboyluo** [ElemeFE/vue-amap#171]
`main.js`
`import VueAMap from 'vue-amap';`
`Vue.use(VueAMap);`

`// 初始化vue-amap`
`VueAMap.initAMapApiLoader({`
  `// 高德的key`
 ` key: 'my-key',`
  `// 插件集合`
 ` plugin: ['Geolocation']`
`});`

`app.vue`
`		<div class="el-vue-amap">
 			<el-amap vid="amap" :plugin="plugin"></el-amap>
 		</div>`
              data () {

		 let self = this;
		return {
		   plugin: [{
	            pName: 'Geolocation',
	            events: {
	              init(map) {
	                //map是高德地图定位插件实例
	                map.getCurrentPosition((status, result) => {
	                  	if (result && result.position) {
	                    	      self.lng = result.position.lng;
	                    	      console.log(self.lng)
	                    	     self.lat = result.position.lat;
	                    	     self.$nextTick();
	                    	    self.onComplete();
	                  	}else{
	                  	      self.onError();
	                  	}
	                });
	              }
	            }
          	}]
		}
	},

**Comment by AxeMea** [comment]
@hiboyluo 

你好，有复现的方式吗

**Comment by hiboyluo** [comment]
您好，暂时还没有，还在开发阶段。也只是偶尔会出现以上的错误，等正式部署的时候，我再测试一下。如果有问题我再反馈。谢谢！

**Comment by Faithree** [comment]
我也遇到了这个问题，真的很奇怪，有没有解决方案？@hiboyluo

**Comment by hiboyluo** [comment]
暂时还没有。不过不是太影响，所以暂时忽略了 @Faithree

**Comment by Faithree** [comment]
已找到解决措施，
setTimeout(function () {
  Vue.use(AMap)
  AMap.initAMapApiLoader()
}, 0)

这样子引入，目前可用

**Comment by gengjiawen** [comment]
我在mounted的时候调用AMap会出这个问题,不知道是否相关
```
ReferenceError: AMap is not defined
    at VueComponent.mounted (eval at <anonymous> (app.js:1807), <anonymous>:30:18)
    at callHook (eval at <anonymous> (app.js:752), <anonymous>:2557:21)
    at Object.insert (eval at <anonymous> (app.js:752), <anonymous>:3384:7)
    at invokeInsertHook (eval at <anonymous> (app.js:752), <anonymous>:5212:28)
    at Vue$3.patch [as __patch__] (eval at <anonymous> (app.js:752), <anonymous>:5377:5)
    at Vue$3.Vue._update (eval at <anonymous> (app.js:752), <anonymous>:2317:19)
    at Vue$3.updateComponent (eval at <anonymous> (app.js:752), <anonymous>:2440:10)
    at Watcher.get (eval at <anonymous> (app.js:752), <anonymous>:2779:25)
    at new Watcher (eval at <anonymous> (app.js:752), <anonymous>:2762:12)
    at mountComponent (eval at <anonymous> (app.js:752), <anonymous>:2444:17)
```
后面改成这么调用了
```vue
  mounted () {
    setTimeout(() => {
      let lnglat = new AMap.LngLat(117.369102, 24.51896)
      this.msg = lnglat.distance([117.684242, 24.50322])
      console.log(this.msg)
    }, 300)
  }
```

**Comment by shidaping** [comment]
这很可能是因为你的amap api js是异步的，官方提供了一个callback回调，将创建地图的代码放在callback里就好。http://lbs.amap.com/api/javascript-api/guide/function/loading。先定义一个init函数，然后加载js。
`<script src="http://webapi.amap.com/maps?v=1.4.0&key=您申请的key值&callback=init"></script>
<script type="text/javascript">

    window.init = function(){
        var map = new AMap.Map('container', {
           center:[117.000923,36.675807],
           zoom:11
        });
    }

</script>`

**Comment by xinsiyou** [comment]
请教一下，el-amap标签是你们自己引入的element的吗

**Comment by jerry-i** [comment]
@xinsiyou 使用了 `el` 这个命名空间而已

**Comment by jerry-i** [comment]
expired issue. closed
