### ISSUE TITLE
随便点击地图任意处，报错：TypeError: Cannot read property 'target' of undefined

### ISSUE THREAD

**Issue by ZhouDH1993** [ElemeFE/vue-amap#172]
我在一个页面中引入了 ```el-amap```, 然后在同一项目的另一个页面中引入```el-amap```的时候，随便点击该地图的任意处，就报```Uncaught TypeError: Cannot read property 'target' of undefined```

**Comment by HanXiaoMa** [comment]
怎么解决的 ？
