### ISSUE TITLE
使用信息窗体报错

### ISSUE THREAD

**Issue by wuhe52** [ElemeFE/vue-amap#173]
地图出不来的时候报错Uncaught (in promise) TypeError: Cannot read property '0' of undefined

跳转到别的页面是报错[Vue warn]: Error in destroyed hook: "TypeError: Cannot read property 'close' of undefined"
found in
---> <ElAmapInfoWindow>
       <ElAmap>

**Comment by AxeMea** [comment]
@wuhe52 

你好，能贴下代码吗
