### ISSUE TITLE
在覆盖物点坐标的click事件中进行‘’.$router.push('home')路由跳转，浏览器报错如何解决？

### ISSUE THREAD

**Issue by jjf464512538** [ElemeFE/vue-amap#174]
mounted () {
    let self = this;
    this.markers = [
      {
        position:  [112.66, 22.68392],
        events: {
          click: function(){
           self.$router.push('home');
          }
        },
        visible: true,
        draggable: false
      }
    ]
  }

Cannot read property 'Ed' of null

**Comment by ExcuseM** [comment]
遇到了相同的问题，怀疑是跳转时还有代码没有执行完成，所以加了一个定时器跳转，解决了问题，希望对你有帮助
setTimeout(() => {
  self.$router.push('home');
}, 200);

**Comment by jjf464512538** [comment]
谢谢你的回答，解决了我的问题。还有个问题，events : {
          init(map) {
            map.getCity(function(result){
              alert(result.cityCode);
            })
报错Cannot read property 'addressComponent' of undefined
