### ISSUE TITLE
点坐标无法替换icon

### ISSUE THREAD

**Issue by jjf464512538** [ElemeFE/vue-amap#177]
data() {
        return {
          zoom: 14,
          center: [121.5273285, 31.21515044],
          markers: [
            {
              icon: "https://www.baidu.com/img/bd_logo1.png",
              position: [121.5273285, 31.21515044],
            }
          ]
        };
      },

**Comment by AxeMea** [comment]
@jjf464512538 

请检查 `icon` 是否绑定模板

**Comment by jjpassion** [comment]
icon 怎么使用icon对象，不使用string
