### ISSUE TITLE
部分地区无法显示卫星图片，可以通过其他API请求卫星地图的瓦片来解决

### ISSUE THREAD

**Issue by AkatQuas** [ElemeFE/vue-amap#179]
代码中只用到了MapType一个插件。在区域无限放大的过程中，出现了如下图情况，请问有什么方法可以修吗？先谢谢了

![screen-shot-2017-07-20-at-20 34 05](https://user-images.githubusercontent.com/24731539/28417781-035e6be6-6d8c-11e7-8b4f-1ec355e6e6b4.jpg)

**Comment by AxeMea** [comment]
@AkatQuas 

这应该是高德地图本身的原因吧，可能是那一块图片资源载入失败了。

**Comment by AkatQuas** [comment]
想到了一个解决办法，在cdn引入的情况下，可以自定义卫星图层加载。
    var sateLayer = new AMap.TileLayer.Satellite({
        map: map,
        zIndex: 3,
        opacity: 1,
        getTileUrl: 'http://www.google.cn/maps/vt?lyrs=s@729&gl=cn&x=[x]&y=[y]&z=[z]',
        detectRetina: true,
    });

暂时没有想到如何在npm引入情况下使用。。

**Comment by AxeMea** [comment]
cdn 和 npm 对于使用这个特性的方式应该是一样的。可以在 `map` 的 `events` 里解决。像这样：

```
events: {
  init(o) {
    let sateLayer = new AMap.TileLayer.Satellite({ map: o, ... });
  }
}
```

**Comment by AkatQuas** [comment]
Agreed!
我发现lazyAMapApiLoaderInstance这个对象的_window下面有个AMap的对象，
亦即原生的高德AMap对象。
应该是在initAMapApiLoader时注入到window对象下面的。

完毕。

**Comment by AkatQuas** [comment]
更新发现
数据处

           map_conf: {
                    ...
                    events:{
                        complete(o) {
                            // 加自定义卫星图图层
                            let sateLayer = new AMap.TileLayer.Satellite({
                                map:amapManager.getMap(),
                                zIndex: 3,
                                opacity: 1,
                                getTileUrl: 'http://www.google.cn/maps/vt?lyrs=s@729&gl=cn&x=[x]&y=[y]&z=[z]',
                                detectRetina: true,
                            });
                        }
                    }
                }


可以做到在当前el-amap不重新渲染的情况下，请求的卫星瓦片来自于谷歌。

**Comment by AxeMea** [comment]
👍 👍 👍
