### ISSUE TITLE
信息窗体内使用@click

### ISSUE THREAD

**Issue by sworddmk** [ElemeFE/vue-amap#183]
问题是这样的:
 目前做到的一个项目 有个要求就是信息窗体 点击的时候跳转到另一个页面去 然而信息窗体是动态生成的 似乎没有办法去绑定vue事件。。。 这种情况下 有什么比较好的处理方式么 还是说只能重写源码或者使用dom操作的方式？

**Comment by AxeMea** [comment]
@sworddmk 

窗体内部目前只能用 dom 操作，不支持 vue 的机制。

**Comment by xinde** [comment]
可以通过.$mount 动态添加组件的dom进去，在组件中methods里调用父级组件中的方法

**Comment by hopkinson** [comment]
@xinde 请问可以写详细吗

**Comment by xinde** [comment]
@hopkinson 大致是这样的，好像现在已经支持了
// var MyComponent = Vue.extend({
          //   template:
          //     '<div id="haha" style="padding:10px;">' +
          //     element.poiName +
          //     "</div>",
          //   methods: {
          //     test() {
          //       //that.testParent();
          //     }
          //   }
          // });

          // **var component = new MyComponent().$mount();**
          // windows.push({
          //   position: element.position.split(","),
          //   **content: component.$el,**
