### ISSUE TITLE
引入高德 UI 组件库不起作用

### ISSUE THREAD

**Issue by clubkus** [ElemeFE/vue-amap#194]
VueAMap.initAMapApiLoader({
  key: 'YOUR_KEY',
  plugin: ['AMap.Scale', 'AMap.OverView', 'AMap.ToolBar', 'AMap.MapType',...],
  uiVersion: '1.0' // 版本号 ---应用到项目中不起作用
});

问题：uiVersion: '1.0' 添加到项目中不起作用，我自己添加UI组件后（如下）
methods:{
	    init: function () {
	    let AMapUIProtocol = 'https:'; 
        let url = 'https://webapi.amap.com/ui/1.0/main.js'
        let script = document.createElement('script')
        script.setAttribute('src', url)
        document.getElementsByTagName('head')[0].appendChild(script)
	    }
    },
		 created(){
		 	this.init()
   }

报错：
ReferenceError: AMapUI is not defined

**Comment by jerry-i** [comment]
请看示例，这里 init 调用有误 https://elemefe.github.io/vue-amap/#/zh-cn/introduction/ui-component

**Comment by clubkus** [comment]
events: {
            init(map) {           	
              	AMapUI.loadUI(['misc/PositionPicker'], function(PositionPicker) {				
			        const positionPicker = new PositionPicker({
			            mode: 'dragMap',
			            map: map
			        });
			
			        positionPicker.on('success', function(positionResult) {
			            document.getElementById('lnglat').innerHTML = positionResult.position;
			            console.log('amaps:'+positionResult.position)
			        });
			        var onModeChange = function(e) {
			            positionPicker.setMode(e.target.value)
			        }
			        var dragMapMode = document.getElementsByName('mode')[0];
			       
			        AMap.event.addDomListener(dragMapMode, 'change', onModeChange)
			        positionPicker.start();		
		    	});
            }
             
        },
不好意思，我是参考按照步骤做的，上面是我的init，一直报错Unhandled promise rejection ReferenceError: 'AMapUI' is undefined

**Comment by chinafatboy** [comment]
问一句，这个问题解决了吗？我也是卡在这里了？
Is this problem already solved? I'm stuck here, too

**Comment by AxeMea** [comment]
在 `.eslintrc` 中配置 
```
globals: {
 "AMapUI": true
}
```

**Comment by chinafatboy** [comment]
嗯，感谢回复，不过我的应该不是这个问题，因为在我这个项目当中没有使用到eslint。

**Comment by caokunyu** [comment]
我用npm 写发现 init 里 AMapUI 没有被调用 
然后在 index.html 引入 ui 和key  那还用 vue-amap 干嘛啊

**Comment by caokunyu** [comment]
@chinafatboy  你的ui 引入了成功了吗

**Comment by jerry-i** [comment]
·0.4.1·已修

**Comment by lxl0302** [comment]
请问大佬问题解决了吗
