### ISSUE TITLE
ssr 刷新时报错 Cannot read property 'load' of null 

### ISSUE THREAD

**Issue by EasonShen1989** [ElemeFE/vue-amap#195]

**Comment by jerry-i** [comment]
刷新指页面刷新？

**Comment by EasonShen1989** [comment]
是的，在nuxt的下，从其他页面调到地图页面没有问题，但是在地图页面手动刷新浏览器，就会报这个错

**Comment by EasonShen1989** [comment]
目前会修复这个bug么？

**Comment by DragWeb** [comment]
我也报这个错误，但是我用的是egg框架

**Comment by jerry-i** [comment]
@DragWeb @EasonShen1989  这边库这里并不能很好的处理的，应该你们业务处理下， 在服务端预渲染的时候不进行地图初始化和相对应的地图操作，需要在具体业务代码中书写。地图逻辑在非浏览器环境无法执行的
```
if (!Vue.prototype.$isServer) {
// loadScript init amap
}
```

**Comment by EasonShen1989** [comment]
这样做 会报另一个错误 The client-side rendered virtual DOM tree is not matching server-rendered content.

**Comment by dongqudamage** [comment]
ssr 请问一下怎么加载vue-amap 这个地图插件

**Comment by DragWeb** [comment]
@dongqudamage vue-amap不支持服务端渲染，会报错

**Comment by nic611** [comment]
同问，能在mount里实例化吗

**Comment by laienliang** [comment]
有解决办法么？我nuxt+vue-amp也遇到一样的问题

**Comment by jerry-i** [comment]
建议写一个 `wrap` 组件进行条件渲染
```js
render() {
  if (Vue.prototype.$isServer)  return placeholderComponent;
  return logicAMapComponent;
}
```
