### ISSUE TITLE
我是参照引入的ui组件库，按照步骤一步一步做的，还是报错

### ISSUE THREAD

**Issue by clubkus** [ElemeFE/vue-amap#197]
VueAMap.initAMapApiLoader({
key: 'YOUR_KEY',
plugin: ['AMap.Scale', 'AMap.OverView', 'AMap.ToolBar', 'AMap.MapType',...],
uiVersion: '1.0' // 版本号
});
events: {
init(map) {
AMapUI.loadUI(['misc/PositionPicker'], function(PositionPicker) {
const positionPicker = new PositionPicker({
mode: 'dragMap',
map: map
});
positionPicker.on('success', function(positionResult) {
document.getElementById('lnglat').innerHTML = positionResult.position;
console.log('amaps:'+positionResult.position)
});
var onModeChange = function(e) {
positionPicker.setMode(e.target.value)
}
var dragMapMode = document.getElementsByName('mode')[0];
	        AMap.event.addDomListener(dragMapMode, 'change', onModeChange)
	        positionPicker.start();		
    	});
    }
     
},
我是参照步骤做的，上面是我的init，amapManager也有添加，一直报错Unhandled promise rejection ReferenceError: 'AMapUI' is undefined，没有实现效果，在index.html里面引入ui组件库就会有效果，我怀疑是初始化ui组件库引入没起作用

**Comment by clubkus** [comment]
我把引入ui组件库的示例照搬到我的项目中测试了一下，还是报错 
Uncaught (in promise) ReferenceError: AMapUI is not defined
    at Object.init (eval at <anonymous> (app.js:2120), <anonymous>:30:11)
    at VueComponent.register (eval at <anonymous> (app.js:1190), <anonymous>:247:56)
    at VueComponent.boundFn [as register] (eval at <anonymous> (app.js:724), <anonymous>:166:12)
    at VueComponent.eval (eval at <anonymous> (app.js:1190), <anonymous>:143:15)
    at VueComponent.Vue.$emit (eval at <anonymous> (app.js:724), <anonymous>:2207:16)
    at eval (eval at <anonymous> (app.js:1190), <anonymous>:2580:16)
    at <anonymous>
init @ amaps.vue?b6a2:28
register @ index.js?1f44:247
boundFn @ vue.esm.js?65d7:165
(anonymous) @ index.js?1f44:143
Vue.$emit @ vue.esm.js?65d7:2206
(anonymous) @ index.js?1f44:2580

**Comment by jianpiao** [comment]
我也是照着官网的cope过去  最后同样显示ReferenceError: AMapUI is not defined   
在官网上显示报错的处理方式： 
若 eslint 报错 AMap is undefined 之类的错误。请将 AMap 配置到 .eslintrc 的 globals 中。

**Comment by bingyuea** [comment]
+1

**Comment by bigzs** [comment]
.eslintrc在哪里?
