### ISSUE TITLE
 线上报错 'ud' of undefined

### ISSUE THREAD

**Issue by MrSuperJ** [ElemeFE/vue-amap#199]
`Uncaught TypeError: Cannot read property 'ud' of undefined
    at main?v=1.3&key=***********&m=http,map,anip,layers,overlay0,brender,mrender,touch,vectorlayer,overlay,cmng,cgl,AMap.Geolocation,AMap.Autocomplete,AMap.PlaceSearch,AMap.PolyEditor,AMap.CircleEditor,sync&vrs=1500628681675:99
    at main?v=1.3&key=**********&m=http,map,anip,layers,overlay0,brender,mrender,touch,vectorlayer,overlay,cmng,cgl,AMap.Geolocation,AMap.Autocomplete,AMap.PlaceSearch,AMap.PolyEditor,AMap.CircleEditor,sync&vrs=1500628681675:104
    at main?v=1.3&key=****************&m=http,map,anip,layers,overlay0,brender,mrender,touch,vectorlayer,overlay,cmng,cgl,AMap.Geolocation,AMap.Autocomplete,AMap.PlaceSearch,AMap.PolyEditor,AMap.CircleEditor,sync&vrs=1500628681675:217`
`in?v=1.3&key=*******&m=http,map,anip,layers,overlay0,brender,mrender,touch,vectorlayer,overlay,cmng,cgl,sync&vrs=1500628681675:159 Uncaught (in promise) TypeError: a[c].split is not a function
    at c.plugin (main?v=1.3&key=**************&m=http,map,anip,layers,overlay0,brender,mrender,touch,vectorlayer,overlay,cmng,cgl,sync&vrs=1500628681675:159)
    at addPlugins (vendor.js?v=201708162348:21)
    at a.n [as addPlugins] (vendor.js?v=201708162348:11)
    at vendor.js?v=201708162348:21
    at <anonymous>`

**Comment by MrSuperJ** [comment]
这个问题只在 发布到服务器上出现  在本地开发状态下没有问题

**Comment by jerry-i** [comment]
这个应该是脚本load的问题？

**Comment by MrSuperJ** [comment]
问题已解决， 是由于js引入了两个不同key的版本 ，谢谢回复
