### ISSUE TITLE
如何才能在点击marker的时候弹出info window

### ISSUE THREAD

**Issue by yzqiang** [ElemeFE/vue-amap#201]
![image](https://user-images.githubusercontent.com/1594490/29496273-d765f5c0-8601-11e7-851c-31256d1d5db4.png)
现在是启动后显示一个info window。
我希望的效果是所有info window默认关闭，点击marker的时候显示info window。
谢谢！

**Comment by yzqiang** [comment]
找到说明代码了，已解决，谢谢！
https://elemefe.github.io/vue-amap/#/zh-cn/examples/windows/info-window

**Comment by yzqiang** [comment]
关闭

**Comment by yzqiang** [comment]
找到说明代码了，已解决，谢谢！
https://elemefe.github.io/vue-amap/#/zh-cn/examples/windows/info-window

**Comment by yzqiang** [comment]
![image](https://user-images.githubusercontent.com/1594490/29496676-505f1cc4-860a-11e7-87c8-65d9568f8136.png)
info window弹出的位置不准，请问如何通过调整offset来让弹出位置更准确？

**Comment by AxeMea** [comment]
@yzqiang 

`info window` 的 `center` 设置后不准？

**Comment by yzqiang** [comment]
是弹出位置，注意尖角指向的位置，正确的应该是在上方，需要做一个offset。

**Comment by airzhanglin** [comment]
@yzqiang info window信息窗体弹出来关闭按钮点击之后设置visible为true后无效。这怎么解决
