### ISSUE TITLE
 Cannot assign to read only property 'exports' of object '#<Object>

### ISSUE THREAD

**Issue by aiwhj** [ElemeFE/vue-amap#202]
想npm引入原生amap
`import { amapManager } from 'vue-amap';`
结果报错
` Cannot assign to read only property 'exports' of object '#<Object>`
好像是在webpack 2中不允许混用import和module.exports

**Comment by handsameliu** [comment]
我是追加安装了es2015，就解决了

**Comment by hopkinson** [comment]
export default 和modules.export都有

**Comment by jerry-i** [comment]
是`umd`的方式额
