### ISSUE TITLE
昨天信息窗口打开正常，今天就报错。。。求解决

### ISSUE THREAD

**Issue by HaoHaoGeXia** [ElemeFE/vue-amap#210]
![image](https://user-images.githubusercontent.com/28550360/29851840-fd435cec-8d68-11e7-8c8c-fd0d27b160e8.png)

**Comment by AxeMea** [comment]
@HaoHaoGeXia 

正在修复。

**Comment by HaoHaoGeXia** [comment]
修复完。。求告知解决方案。。。辛苦辛苦

**Comment by Liucz0819** [comment]
vue-amap包下的amap-info-window.vue中，解决重新打开窗口方法报错
![image](https://user-images.githubusercontent.com/31462754/29853462-adb29e86-8d72-11e7-9403-da4837d33bc8.png)
this.G is undefined ，测试修改为 this.F.map是好用的，求大神修复一下

**Comment by HaoHaoGeXia** [comment]
谢谢Liucz0819 ，经测试可行

**Comment by AxeMea** [comment]
@HaoHaoGeXia @Liucz0819 

请更新至 `0.3.1` 已经修复。
