### ISSUE TITLE
定位按钮位置

### ISSUE THREAD

**Issue by gottayan** [ElemeFE/vue-amap#215]
怎么修改默认定位按钮的位置？

**Comment by AxeMea** [comment]
@gottayan 

你好，提供下截图或者代码。

**Comment by gottayan** [comment]
- 
![kkfyjeprxvun i3wjxup02e](https://user-images.githubusercontent.com/23098167/29908584-9cfcd51a-8e54-11e7-8e1e-5b4341919d82.png)

**Comment by AxeMea** [comment]
样式覆盖吧

```
.amap-geolocation-con {
  top: 0 !important
}
```

**Comment by gottayan** [comment]
谢谢，已解决。buttonOffset: {x: 0, y: 0}也可以。
