### ISSUE TITLE
非常紧急，如何不在main.js加载？

### ISSUE THREAD

**Issue by michaelzhouh** [ElemeFE/vue-amap#217]
其实我用到地图的地方，就一个vue页面，但是所有示例都是在main.js添加的该组件
```
import AMap from 'vue-amap';
// 初始化vue-amap
AMap.initAMapApiLoader({
  // 高德的key
  key: '……',
  // 插件集合
  plugin: ['AMap.Autocomplete', 'AMap.PlaceSearch', 'AMap.Geolocation']
});
Vue.use(AMap)
```

这样导致打包之后vendor.***.js 太大了，而且完全没必要。如何才能只在那个要使用地图的vue页面，再加载啊？

**Comment by AxeMea** [comment]
如果不想全局初始化，你可以把初始化的步骤放到组件的 `beforeCreated` 的 hook 里。

另外，`vue-amap ` 体积不大。如果想减少 `vendor` 可以通过 `code splitting`。

**Comment by jerry-i** [comment]
可以写个初始化的函数，在使用的页面调用

**Comment by michaelzhouh** [comment]
我的改动如下，删除掉了main.js的哪些AMap引入和初始化代码。
在我使用的vue页面上：
`import AMap from 'vue-amap';
import Vue from 'vue';
beforeCreate() {
    // 初始化vue-amap
      AMap.initAMapApiLoader({
        // 高德的key
        key: '……',
        // 插件集合
        plugin: ['AMap.Autocomplete', 'AMap.PlaceSearch', 'AMap.Geolocation']
      });
      Vue.use(AMap)
    },
mounted() {
       AMap.service(["AMap.Geolocation"], function() {
            var geolocation = new AMap.Geolocation({ //这一行就报错
              enableHighAccuracy: true,
              timeout: 10000
            })
           ……
}
`
浏览器F12，报错的那一行，显示的是：Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_3_vue_amap___default.a.service is not a function
    at eval (eval at <anonymous> (app.js:3150), <anonymous>:81:58)

请问怎么改啊？

**Comment by AxeMea** [comment]
`import AMap from 'vue-amap'` => `import VueAMap from 'vue-amap'`

**Comment by ruanjf** [comment]
延迟加载组件（使用了猥琐的方式😌）

1. 创建一个`amap.js`
1. `import`需要的组件

创建文件
```js
// amap.js
import Vue from 'vue'

let VueAMap
function promiseAMapComponent (comp) {
  return () => {
    if (VueAMap) {
      return Promise.resolve(VueAMap[comp])
    } else {
      return import(/* webpackChunkName: "amap" */ 'vue-amap').then(vam => {
        if (!VueAMap) {
          // 模拟Vue并代替插件初始化
          vam.default.install({
            config: JSON.parse(JSON.stringify(Vue.config)),
            component () {}
          }, {})
          // vue-amap初始化
          vam.initAMapApiLoader(config)
          VueAMap = vam.default
        }
        return VueAMap[comp]
      })
    }
  }
}

export const config = {
  key: 'YOUR_KEY',
  plugin: ['AMap.Scale', 'AMap.OverView', 'AMap.ToolBar', 'AMap.MapType',...]
}

export const Amap = promiseAMapComponent('Amap')
export const AmapMarker = promiseAMapComponent('AmapMarker')
export const AmapSearchBox = promiseAMapComponent('AmapSearchBox')
export const AmapCircle = promiseAMapComponent('AmapCircle')
export const AmapGroundImage = promiseAMapComponent('AmapGroundImage')
export const AmapInfoWindow = promiseAMapComponent('AmapInfoWindow')
export const AmapPolygon = promiseAMapComponent('AmapPolygon')
export const AmapPolyline = promiseAMapComponent('AmapPolyline')

```
导入使用
```js
import {config as amapConfig, Amap, AmapMarker, AmapSearchBox} from 'amap.js'
// 如果需要可以覆盖配置
amapConfig.key = 'YOUR_OTHER_KEY'

export default {
  components: {
    Amap,
    AmapMarker,
    AmapSearchBox
  },
  created () {}
}
```

**Comment by devondahon** [comment]
@ruanjf  I get this error message when using your code:

```
ERROR in ./resources/assets/js/amap.js
Module build failed: SyntaxError: Unexpected token (9:13)

   7 |       return Promise.resolve(VueAMap[comp])
   8 |     } else {
>  9 |       return import(/* webpackChunkName: "amap" */ 'vue-amap').then(vam => {
     |              ^
  10 |         if (!VueAMap) {
  11 |           // 模拟Vue并代替插件初始化
  12 |           vam.default.install({
```

**Comment by ruanjf** [comment]
@devondahon `import()` function is not support, you can use `Promise` to wrap `require()` or use [babel-plugin-dynamic-import-webpack](https://github.com/airbnb/babel-plugin-dynamic-import-webpack) plugin
