### ISSUE TITLE
What the Map base (Google)?

### ISSUE THREAD

**Issue by thearabbit** [ElemeFE/vue-amap#219]
What the Map base (Google or Not)?

**Comment by thearabbit** [comment]
Could I use for `Khmer/Camdia`?

**Comment by one-pieces** [comment]
Not Google map...
It bases AMap [高德地图](http://lbs.amap.com/) from Alibaba. It is nicely used for `China`, but not sure for `Khmer/Camdia`.

**Comment by thearabbit** [comment]
Thanks for your reply.
