### ISSUE TITLE
点坐标的icon和content都不能生效，是什么情况

### ISSUE THREAD

**Issue by Perrywzp** [ElemeFE/vue-amap#22]
![image](https://cloud.githubusercontent.com/assets/10015609/21675933/b40ea52c-d36e-11e6-9794-3c9a384db6bd.png)
一开始用的是html编写，现在直接用高德地图的icon方法，也是无效！不知错在何处...

**Comment by Perrywzp** [comment]
嗯嗯，这招也试过了，没有生效

**Comment by Perrywzp** [comment]
![Uploading image.png…]()
看了下源码，我想应该是这个吧。。。

**Comment by jerry-i** [comment]
`content`用字符串应该是可以的我刚刚试了下，你看你的属性有没有绑定上去
```
<el-amap vid="amap" :zoom="zoom" :center="center">
          <el-amap-marker v-for="marker in markers" :content="marker.content" :position="marker.position" :events="marker.events" :visible="marker.visible" :draggable="marker.draggable"></el-amap-marker>
        </el-amap>
```
直接生成对象这个promise是有的;如果有这个需求回头把文档放出来

**Comment by Perrywzp** [comment]
嗯嗯，确实是没有绑，感谢！
脚本load完毕的这个promise我在源码里是看到了, 觉得文档可以放一放。（当然content也已经可以满足业务需求了）

**Comment by jerry-i** [comment]
好的，回头我完善下
