### ISSUE TITLE
无法引入高德组件库1.4.0，高德官方改请求地址了。。。。

### ISSUE THREAD

**Issue by KarnaughK** [ElemeFE/vue-amap#223]
引入高德组件库1.4.0的时候发现报错了
![image](https://user-images.githubusercontent.com/13878673/30684904-9a0d9aa0-9ee5-11e7-8c4c-2d5f1c954bce.png)

但是用例子里的1.0就没事。。。

于是去看了眼[高德官网](http://lbs.amap.com/api/javascript-api/summary/) （最底下）
发现
![image](https://user-images.githubusercontent.com/13878673/30684966-d4e9c7d4-9ee5-11e7-9cca-0d6850e59cd8.png)

麻烦作者更新一下了。。。。

**Comment by KarnaughK** [comment]
> 从 V1.4.0 版本开始，JS API 支持分版本加载功能，API 升级不会再强制用户升级，用户可以保持当前版本继续使用。修改方式如下：更改地址中参数 v 的取值即可。
> `<script type="text/javascript" src="http://webapi.amap.com/maps?v=1.4.0&key=您申请的key值"></script>
> `

**Comment by KarnaughK** [comment]
@jerry-i @AxeMea 如果可以的话，麻烦尽快解决一下，正在基于你们的库开发。。。万分感谢

**Comment by jerry-i** [comment]
![image](https://user-images.githubusercontent.com/11937539/30685785-9e9df6de-9ee8-11e7-9f1c-6da688d025d4.png)
初始化的时候加个v参数

**Comment by KarnaughK** [comment]
![image](https://user-images.githubusercontent.com/13878673/30688341-74343f18-9ef0-11e7-91a1-063072c8fa8c.png)

谢谢，我这么引入以后是好了，但是提示我找不到 AMapUI 。。。。如果我把`uiVersion: '1.4.0'`这条放开，就又回到之前的报错了。。。

![image](https://user-images.githubusercontent.com/13878673/30688435-b7946fee-9ef0-11e7-8948-308860dc4557.png)
![image](https://user-images.githubusercontent.com/13878673/30688469-d6d49578-9ef0-11e7-8eaa-ba5b3107ff76.png)

**Comment by jerry-i** [comment]
uiVersion 暂时有个bug。O__O "…，建议自己在init方法里异步load`main-async`的脚本

```js
const script = document.createElement('script')
script.src = '//webapi.amap.com/ui/1.0/main-async.js '; 
script.onload = () => {/* your bussuniess logic*/}
document.head.append(script);
```

**Comment by KarnaughK** [comment]
O_O 好的。我先试试能不能成功。。。。还是希望你们尽快修好~毕竟我js水平不咋地不一定能弄好。。哈哈:p

**Comment by bingyuea** [comment]
+1 ，现在依然存在
