### ISSUE TITLE
请问怎么在这个框架上面使用Geocoder类，LngLat类的功能呢？

### ISSUE THREAD

**Issue by pylee** [ElemeFE/vue-amap#229]
我再vue文件里面这样使用
`var geocoder = new AMap.Geocoder({})`
会报错 AMap.Geocoder is not a constructor，文档又没有这一块功能的使用demo，请问应该如何使用这些类呢？

**Comment by jerry-i** [comment]
脚本是延迟加载的，要在 init 之后或者在 https://elemefe.github.io/vue-amap/#/zh-cn/introduction/init 这个promise之后
