### ISSUE TITLE
Missing interface to manual manipulate plugins?

### ISSUE THREAD

**Issue by thenlai** [ElemeFE/vue-amap#23]
I was trying to use a `ToolBar` plugin and set properties for it.

In vanillaJS I can use it like:

```js
const toolBar = new window.AMap.ToolBar({ visible: true })
toolBar.hideDirection()
toolBar.hideRuler()

// then add it to the map:
// this.map.addControl(toolBar)
```

How can it achieve the same with `vue-amap`. I don't think it is provided in the API docs.

I just read:

```html

<el-amap :plugin="plugin">

<script>
{
   plugin: ['ToolBar']
}
</script>
```

and things like `plugin: ['ToolBar.hideDirection']` won't work.

---

请问一下，如何自定义设置plugins？

比如我想对ToolBar进行进一步的设定，使用原生的地图接口。

**Comment by AxeMea** [comment]
你好，对于插件的配置，我们正在做。后续会提供类似这样的方式：
```
<el-amap :plugin="plugin">

{
   plugin: [
      'AMap.Scale',  
      {
         name: 'ToolBar',
         locate: true
      }
   ]
}
```

这样就应该能满足你的需求了。

**Comment by AxeMea** [comment]
@thenlai , hi 最新v0.1.2 版本支持自定义配置插件，细节可查看文档。
