### ISSUE TITLE
ios 11定位问题

### ISSUE THREAD

**Issue by Adolph-lh** [ElemeFE/vue-amap#233]
在ios 11下无法定位，切换了https还是这样

高德官方给出的修复方法如下，希望尽快修复下
您好，如果是的话，请在其中使用iOS11操作系统尝试访问如下页面：
http://a.amap.com/jsapi_demos/static/remogeo/remo.html

重点需要关注的代码是：
Java
// ios环境切换到使用远程https定位
if (AMap.UA.ios && document.location.protocol !== 'https:') {

//使用远程定位，见 remogeo.js，http://a.amap.com/jsapi_demos/static/remogeo/remogeo.js
var remoGeo = new RemoGeoLocation();

//替换方法
navigator.geolocation.getCurrentPosition = function() {
return remoGeo.getCurrentPosition.apply(remoGeo, arguments);
};

//替换方法
navigator.geolocation.watchPosition = function() {
return remoGeo.watchPosition.apply(remoGeo, arguments);
};
}

**Comment by Adolph-lh** [comment]
这个bug大概什么时候修复？

**Comment by xueyeqing** [comment]
请问大概什么时候可以解决吗？

**Comment by coco128** [comment]
定位偏差有点大

**Comment by jerry-i** [comment]
`0.4.1` 已修复
