### ISSUE TITLE
您好，用AMapManager怎么拿到高德实例呢

### ISSUE THREAD

**Issue by MaBillion** [ElemeFE/vue-amap#237]
ƒ AMapManager() {
    _classCallCheck(this, AMapManager);

    this._componentMap = new Map();
    this._map = null;
  }
他只是一个构造函数，并没有getMap()方法

**Comment by AxeMea** [comment]
@MaBillion 

你好，https://elemefe.github.io/vue-amap/#/zh-cn/introduction/compatible
