### ISSUE TITLE
info-window里面的content能否支持VNode?

### ISSUE THREAD

**Issue by 540240126** [ElemeFE/vue-amap#243]
如题

**Comment by AxeMea** [comment]
暂时不支持，你可以将 `component` 手动 `mount` 到 `info-window` 的 `dom` 节点里面。

**Comment by 540240126** [comment]
好的，多谢告知

**Comment by AxeMea** [comment]
@540240126 

https://github.com/ElemeFE/vue-amap/issues/251

这里有个解决的思路

**Comment by AxeMea** [comment]
@540240126 

你好。

https://elemefe.github.io/vue-amap/#/zh-cn/examples/windows/info-window-template

升级最新版，可以尝试下这个特性

**Comment by 540240126** [comment]
@AxeMea 你好, 为啥不直接弄成jsx那种语法呢， 这样还能获得编译器语法高亮效果
