### ISSUE TITLE
info-window需要新的支持

### ISSUE THREAD

**Issue by nonefirst** [ElemeFE/vue-amap#244]
info-window的内容只支持content展示，能否增加支持标签内容展示。
例：
<el-amap-info-window v-for="window in windows" :position="window.position"  :visible="window.visible" :events="window.events">
<el-row>
    <el-col>
        <el-button>test button<el-button>
    </el-col>
</el-row>
</el-amap-info-window>
能把内部内容展示出来。

**Comment by AxeMea** [comment]
@nonefirst 

你所需要的【标签内容】展示和 `content` 有啥本质的区别吗

**Comment by nonefirst** [comment]
自定义的好用些，例如我可以使用v-for来循环处理数据 并使用this来指引data里面的数据

**Comment by nonefirst** [comment]
<el-col :span="24" :xs="24" :sm="24">
                            <el-button type="primary" v-for="(item, index) in functions"
                                       @click="publish(item.device_send_function_id,clientId)">{{item.button_name}}
                            </el-button>
                        </el-col>

**Comment by nonefirst** [comment]
content可能就需要拼凑代码写了，而且方法里面传入obj大概率是需要转换json字符串

**Comment by AxeMea** [comment]
哦，你是想在 `content` 里放 `Vue` 的组件。

不过，目前不支持，你可以手动 `mount` 将组件编进 `content` 里面。

这方面，我们也在想解决方案。

**Comment by nonefirst** [comment]
哦~~  好的。
