### ISSUE TITLE
AMap.LngLat is not a constructor问题

### ISSUE THREAD

**Issue by oConnerCooper** [ElemeFE/vue-amap#246]
官网文档里，刷新页面，有概率出现“AMap.LngLat is not a constructor”的报错，地图crash了。[截屏](http://wx3.sinaimg.cn/mw690/006eDbRsgy1fl2nzjzb23j31kw0skae9.jpg)

**Comment by AxeMea** [comment]
会不会是高德地区网络问题导致高德的 sdk 脚本没有请求到。

**Comment by jerry-i** [comment]
更新下0.4.1
