### ISSUE TITLE
延时加载聚合效果是否合理 还望解释

### ISSUE THREAD

**Issue by zxb5102** [ElemeFE/vue-amap#249]
在坐标点的聚合章节看到下面的示例代码 
              setTimeout(() => {
                console.log(self.markerRefs);
                let cluster = new AMap.MarkerClusterer(o, self.markerRefs,{
                  gridSize: 80,
                  renderCluserMarker: self._renderCluserMarker
                });
                console.log(cluster);
              }, 1000);
上面的代码使用 延时加载聚合效果 
生产环境中 网络比价卡加载数据比较慢 导致1s后获取的坐标点为空
最后不能够出现聚合效果

之后我想着在加载完数据后设置坐标点聚合
出现下面错误
[Vue warn]: Error in mounted hook: "ReferenceError: AMap is not defined"

请教这种问题怎么解决

**Comment by AxeMea** [comment]
@zxb5102 

你好，不好意思回复慢了。延迟具体时间加载并不是一个最佳的做法，应该在一个合适的生命周期节点执行此类操作。

**Comment by jerry-i** [comment]
已修，现在应该不需要延时

**Comment by cjj0619** [comment]
> 在坐标点的聚合章节看到下面的示例代码
> setTimeout(() => {
> console.log(self.markerRefs);
> let cluster = new AMap.MarkerClusterer(o, self.markerRefs,{
> gridSize: 80,
> renderCluserMarker: self._renderCluserMarker
> });
> console.log(cluster);
> }, 1000);
> 上面的代码使用 延时加载聚合效果
> 生产环境中 网络比价卡加载数据比较慢 导致1s后获取的坐标点为空
> 最后不能够出现聚合效果
> 
> 之后我想着在加载完数据后设置坐标点聚合
> 出现下面错误
> [Vue warn]: Error in mounted hook: "ReferenceError: AMap is not defined"
> 
> 请教这种问题怎么解决

这个问题现在解决了吗？？
