### ISSUE TITLE
信息窗体content里的元素如何写入click事件

### ISSUE THREAD

**Issue by hopkinson** [ElemeFE/vue-amap#251]
`window.push({
content: '<button @click="openVideo(item, i)">视频播放</button>'
})`

**Comment by hopkinson** [comment]
怎么将 component 手动 mount 到 info-window 的 content 里。

**Comment by AxeMea** [comment]
@hopkinson 

目前不支持这种方式，比较快速的方式是，不通过 Vue 的绑定机制，手动绑定 dom 事件。

**Comment by hopkinson** [comment]
![image](https://user-images.githubusercontent.com/13248613/32429239-aca302ac-c304-11e7-89d7-81b1913ffa68.png)
手动绑定 dom 事件了，但handleOpenVideo报undefined

**Comment by AxeMea** [comment]
@hopkinson 

其实我本意是通过 `zepto` 等库来绑定，但感觉还是不够好，还是基于 `vue` 机制来玩最佳，后面我们会重点支持，看 issue 想让 `content` 支持 `template` 的需求很多。

我临时想了一种方式你可以参考下。

```
let node = Vue.compile('<span @click="handler">121212</span>');
let vNode = new Vue({
  methods: {
    handler() {
      alert('i am here')
    }
  },
  render: node.render
});
let dom = document.createElement('span');
let el = vNode.$mount(dom).$el;
      
this.windows.push({
   position: [121.59996, 31.197646],
   content: el
});
```

你可以尝试下。

**Comment by AxeMea** [comment]
@hopkinson 

你好。

https://elemefe.github.io/vue-amap/#/zh-cn/examples/windows/info-window-template

升级最新版，可以尝试下这个特性

**Comment by dinfer** [comment]
@AxeMea 如果template要写成一个.vue文件, 那么怎么加载它呢?
比如我把地图的弹窗写到一个.vue文件里, 希望在map.vue里引用它, 我该如何做呢?

**Comment by AxeMea** [comment]
@dinfer 

可以用类似如下代码试试。

```
import YourComponent from 'YourComponet.vue'
let component = new Vue(YourComponent)
info.content = component.$mount();
```

**Comment by dinfer** [comment]
@AxeMea 万分感谢!
