### ISSUE TITLE
地图一进去就关键字搜索怎么弄？

### ISSUE THREAD

**Issue by Wilson-hu** [ElemeFE/vue-amap#252]
原生的高德地图是这样的
var map = new AMap.Map("container", {
        resizeEnable: true
    });
    AMap.service(["AMap.PlaceSearch"], function() {
        var placeSearch = new AMap.PlaceSearch({ //构造地点查询类
            pageSize: 5,
            pageIndex: 1,
            city: "010", //城市
            map: map,
            panel: "panel"
        });
        //关键字查询
        placeSearch.search('方恒');
    });
但是vue-amap的例子是有一个搜索框，搜索后才触发placeSearch，而不是一进去就根据后台传来的地址，地图上显示对应的位置，请问这个怎么弄？

**Comment by Fzyfeng** [comment]
+1  我模拟点击也不行

**Comment by jjjachyty** [comment]
+1

**Comment by jerry-i** [comment]
这个组件后来还是不考虑维护了；
可以参考下自定义组件的 第二个自己弄个维护下
https://elemefe.github.io/vue-amap/#/zh-cn/custom/custom

也欢迎提 PR
