### ISSUE TITLE
清空地图 clearMap()如何使用

### ISSUE THREAD

**Issue by bingyuea** [ElemeFE/vue-amap#262]
如何清空地图，我知道是clearMap()这个方法；在vue-map里面如何执行拿到这个对象执行该方法，最好有个完整的例子，$$getInstance()这个函数我也知道，官方文档已看过，求解答

**Comment by AxeMea** [comment]
https://elemefe.github.io/vue-amap/#/zh-cn/base/amap

用 `amapManager` 去拿高德实例，然后 `clearMap`
