### ISSUE TITLE
图片覆盖物  与 引入 插件 冲突  

### ISSUE THREAD

**Issue by bingyuea** [ElemeFE/vue-amap#263]
插件和 地图上的图片覆盖物 有冲突， 同时 只能存在一个 ？？？ 在地图覆盖物上面加入这个 :plugin="plugins"， 图片覆盖物就无法加载 ，是我使用的姿势不对吗？

**Comment by AxeMea** [comment]
地图覆盖物并没有 `plugin` 这个属性

**Comment by bingyuea** [comment]
<el-amap vid="amap" :zoom="zoom" :center="center" class="amap-demo"  :plugin="plugins"  >
                    
                    

                    
                    <el-amap-polygon v-for="(polygon, index) in polygons" :vid="index" :ref="`polygon_${index}`" :path="polygon.path" :events="polygon.events">

                    </el-amap-polygon>
                </el-amap>

——————————————————————————————————————————————
地图覆盖物是没有这个属性，我是把这个属性加在el-amap 上面的，图片覆盖加载不出来，把这个属性去掉就可以加载；

**Comment by AxeMea** [comment]
@bingyuea 

你好，方便把代码贴全一点吗，貌似没有闭合。

**Comment by bingyuea** [comment]
`<template>
    <div class="amap-page-container">
      <el-amap vid="amap" :zoom="zoom" :center="center" class="amap-demo" :plugin="plugins">
        <el-amap-ground-image v-for="groundimage in groundimages" :url="groundimage.url" :bounds="groundimage.bounds" :events="groundimage.events"></el-amap-ground-image>
      </el-amap>
    </div>
  </template>

  <style>
    .amap-demo {
      height: 300px;
    }
  </style>

  <script>
    module.exports = {
      data () {
        return {
          zoom: 7,
          center: [121.5273285, 31.21515044],
          groundimages: [
            {
              url: '//faas.elemecdn.com/desktop/media/img/appqc.95e532.png',
              bounds: [[121.5273285, 31.21515044], [122.9273285, 32.31515044]],
              events: {
                click() {
                  alert('click groundimage');
                }
              }
            }
          ]
        }
      }
    };
</script>`
-------------------------------------------------------------------------------------------------------------------
你好，情况是这样的，我只是在 el-amap 这个标签上面绑定了 :plugin="plugins" 这个属性，图片覆盖就加载不出来

**Comment by bingyuea** [comment]
`<el-amap vid="amap" :zoom="zoom" :center="center" class="amap-demo" :plugin="plugins">
            <el-amap-ground-image v-for="groundimage in groundimages" :url="groundimage.url" 
                  :bounds="groundimage.bounds" :events="groundimage.events">
                  </el-amap-ground-image>
 </el-amap>`
-------------------------------------------------------------------------------------------------------------------
你好，情况是这样的 ：这是在 [文档](https://elemefe.github.io/vue-amap/#/zh-cn/coverings/ground-image) 摘取的代码，加上了一个] :plugin="plugins"属性，图片覆盖加载不出来，把这个属性去掉就可以加载；

**Comment by AxeMea** [comment]
`plugins` 你传了什么

**Comment by bingyuea** [comment]
MapType ，OverView ，ToolBar 这三个

**Comment by AxeMea** [comment]
`MapType` 这个插件的锅，你去掉试试

**Comment by bingyuea** [comment]
是这样的
