### ISSUE TITLE
移动端的适配，刷新出不来东西，这个没有一个人碰到过吗？

### ISSUE THREAD

**Issue by xiao0mai** [ElemeFE/vue-amap#266]
就是加入<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no" />，使用google浏览器，按F12模拟手机，就显示不出来东西。

**Comment by xiao0mai** [comment]
老大，给一个完整的可运行的例子哦，运行起来老感觉怪怪的，都不知道错在哪。

**Comment by simplees** [comment]
使用的版本是："vue-amap": "^0.4.1" 同样出现这个问题

**Comment by niuxi091** [comment]
更新到0.4.1版本出现这个问题了

**Comment by cbtpro** [comment]
只在0.4.1这个版本有这个问题，我也碰到了，解决方法
1、不用vue-amap，自己写promise，然后普通的初始化地图
2、使用0.4.0，但是我使用它时也有其他的致命bug，所以使用了0.3.1
等到这个bug关闭后，再升级新版本

**Comment by xiao0mai** [comment]
非常感谢大家的回复，看到这么中文回复，真心感觉强大，老大出来也回个话哦

**Comment by LouisYis** [comment]
谢谢楼上 @cbtpro 大神，找了一个上午快崩溃了都，从0.41版本还原到0.3.1版本，可以在google模拟器下刷新后保持正常

**Comment by jerry-i** [comment]
贴下报错呢。我这复现不了

**Comment by jerry-i** [comment]
dsdas
