### ISSUE TITLE
AMAP_READY_EVENT": "ReferenceError: AMapUI is not defined"

### ISSUE THREAD

**Issue by America-first-melon** [ElemeFE/vue-amap#267]
"vue-amap": "^0.4.1",

![Uploading image.png…]()

**Comment by America-first-melon** [comment]
VueAMap.initAMapApiLoader({
  key: mapKey,
  plugin: ['Geocoder','AMap.Autocomplete', 'AMap.PlaceSearch', 'AMap.OverView', 'AMap.ToolBar', 'AMap.MapType', 'AMap.PolyEditor'],
  uiVersion:'1.0'
});

Vue.use(VueAMap);

**Comment by America-first-melon** [comment]
let amapManager = new VueAMap.AMapManager();
    export default {
        data(){
          let _this = this;
          return {
              loading: false,
              amapManager: amapManager,
              events:{
                init(map){
                  
                  AMapUI.loadUI(['overlay/SimpleMarker'], function(SimpleMarker) {
                const marker = new SimpleMarker({
                  iconLabel: 'A',
                  iconStyle: 'red',
                  map: map,
                  position: map.getCenter()
                });
              });
                  console.log(map)

**Comment by jkaltopp** [comment]
我也是这样问题.....AMapUI is not defined

**Comment by qi19901212** [comment]
初始化的时候需要添加ui版本库才可以使用    uiVersion: '1.0',

**Comment by MuYi086** [comment]
https://elemefe.github.io/vue-amap/#/zh-cn/introduction/ui-component
我把main.js改成了文档页提供的uiVersion: '1.0.11'，然后就好了，大家可以参考一下，不一定通用
