### ISSUE TITLE
在vue-amap中如何使用Geocoder插件

### ISSUE THREAD

**Issue by heroyanglonghui** [ElemeFE/vue-amap#271]
```
AMap.service('AMap.Geocoder',function(){//回调函数
    //实例化Geocoder
    geocoder = new AMap.Geocoder({
        city: "010"//城市，默认：“全国”
    });
    //TODO: 使用geocoder 对象完成相关功能
})
//逆地理编码
var lnglatXY=[116.396574, 39.992706];//地图上所标点的坐标
geocoder.getAddress(lnglatXY, function(status, result) {
    if (status === 'complete' && result.info === 'OK') {
       //获得了有效的地址信息:
       //即，result.regeocode.formattedAddress
    }else{
       //获取地址失败
    }
});  
```
如何在vue-amap 使用geocoder 的方法getAddress

**Comment by jerry-i** [comment]
建议写成util方法
```js
let geocoder = null;
export function getAddress(center) {
  if (Array.isArray(center)) center = new AMap.LngLat(center[0], center[1]);
  return new Promise((resolve, reject) => {
    startLoading();
    const resolveMethod = () => {
      geocoder.getAddress(center, (status, result) => {
        stopLoading();
        if (status === 'complete' && result.info === 'OK') {
          let addressComponent = result.regeocode.addressComponent;
          resolve({
            province: addressComponent.province,
            city: addressComponent.city,
            district: addressComponent.district,
            cityCode: addressComponent.adcode
          });
        } else {
          reject(result);
        }
      });
    };
    if (!geocoder) {
      lazyAMapApiLoaderInstance.load().then(_ => {
        geocoder = new AMap.Geocoder({});
        resolveMethod();
      });
    } else {
      resolveMethod();
    }
  });
}

```

**Comment by lvgao2012** [comment]
AMap.initAMapApiLoader({
    key: 'xxx',
    plugin: ['AMap.Autocomplete', 'AMap.PlaceSearch', 'AMap.Scale', 'AMap.OverView', 'AMap.ToolBar', 'AMap.MapType', 'AMap.PolyEditor', 'AMap.CircleEditor', 'AMap.Geocoder']
})

加入AMap.Geocoder

**Comment by airzhanglin** [comment]
@lvgao2012 我加了AMap.Geocoder之后还是有报AMap.Geocoder is not a constructor错误。请问大神这怎么解决，很急

**Comment by lvgao2012** [comment]
不清楚呢，我用着正常啊

**Comment by airzhanglin** [comment]
@lvgao2012 只要在main.js中AMap.initAMapApiLoader加入AMap.Geocoder就行了吗

**Comment by lvgao2012** [comment]
@airzhanglin 我是那么做的

**Comment by airzhanglin** [comment]
@lvgao2012 能加qq号码吗，帮忙指导一下

**Comment by airzhanglin** [comment]
@heroyanglonghui 楼主解决了这个问题吗？

**Comment by chenjiejing** [comment]
@lvgao2012 我这边在mainjs加入了AMap.Geocoder,还是会报错AMap.Geocoder is not a constructor

**Comment by chenjiejing** [comment]
@airzhanglin 请问你解决了这个问题了吗?我在main.js加入了AMap.Geocoder,使用官网文档的demo还是报AMap.Geocoder is not a constructor

**Comment by broderickwang** [comment]
有解决方案么？

**Comment by anihCevol** [comment]
> 有解决方案么？
这样操作我好像实现了：
1  main.js :
VueAMap.initAMapApiLoader({
  key: "XXXXXXXX",
  plugin: ["AMap.Geocoder"],
  // 默认高德 sdk 版本为 1.4.4
  v: "1.4.4"
});
2  在需要使用Geocoder的页面：
`import { lazyAMapApiLoaderInstance } from "vue-amap";
  lazyAMapApiLoaderInstance.load().then(() => {    
     AMap.plugin("AMap.Geocoder", function() {    //直接把高德官网文档代码copy过来的~~      
          var geocoder = new AMap.Geocoder();
          geocoder.getLocation('南京市汇智大厦', function(status, result) {
              if (status === "complete" && result.info === "OK") {
                // result中对应详细地理坐标信息
                console.log(result);
              } else {
                console.log("未查到相关地址");
              }
            }
          );
        });
      });`
