### ISSUE TITLE
npm 方式引入插件、说未定义

### ISSUE THREAD

**Issue by Jandaes** [ElemeFE/vue-amap#274]
```typescript
/* 全局引入AMap插件 */
Vue.use(VueAMap);
/* 初始化AMap插件配置 */
VueAMap.initAMapApiLoader({
  key: 'YOUR_KEY',
  plugin: ['AMap.Scale', 'AMap.OverView', 'AMap.ToolBar', 'AMap.MapType']
});
let amapManager = new VueAMap.AMapManager();
```
这里说`VueAMap`未定义

**Comment by jerry-i** [comment]
import 了么

**Comment by Jandaes** [comment]
@jerry-i  当然、main.js 已经import了

**Comment by AxeMea** [comment]
这样有问题？

```
import VueAMap from 'vue-amap';
```

先把 `let amapManager = new VueAMap.AMapManager();` 去掉呢

**Comment by Jandaes** [comment]
@AxeMea 如果注释掉这个段 `let amapManager = new VueAMap.AMapManager();` 是没问题，
就是地图一闪而过

**Comment by AxeMea** [comment]
@Jandaes 

一闪而过？ - -

**Comment by weidadedawei** [comment]
我之前也是一闪而没，定位是样式问题，加个scoped
![image](https://user-images.githubusercontent.com/25583243/34284316-f63922e0-e70b-11e7-93ce-72229d29077c.png)
