### ISSUE TITLE
移动端适配问题

### ISSUE THREAD

**Issue by chenmingzeng** [ElemeFE/vue-amap#288]
apple的产品下貌似显示一片空白，貌似apple产品下什么都没做。
"vue-amap": "^0.4.2"
![image](https://user-images.githubusercontent.com/22519203/33699952-48723162-db51-11e7-93e4-a5060baec962.png)
![image](https://user-images.githubusercontent.com/22519203/33699991-6f29c1a8-db51-11e7-84ab-61c10163be44.png)

**Comment by AxeMea** [comment]
有什么报错吗

**Comment by jerry-i** [comment]
0.4.4 ，更新下

**Comment by pandaljf** [comment]
我也遇到这个情况了，amap版本是0.5.2，ios版本10.0.3

**Comment by chenmingzeng** [comment]
我把地图版本搞到最新的，就没问题了。你可以试试

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
