### ISSUE TITLE
引入ui库1.0.11的就报错404,

### ISSUE THREAD

**Issue by 540240126** [ElemeFE/vue-amap#289]
现在出现个问题，就是轨迹展示后切换地图类型轨迹就消失了，我在官方例子上面切换并不会这样，所以我怀疑是版本的问题，但是我把1.0改成1.0.11就报错，network显示404找不到1.0.11文件, 1.0的就可以正常使用

**Comment by jerry-i** [comment]
具体版本号见 http://lbs.amap.com/api/javascript-api/guide/amap-ui/intro

ps：本库的定位只是一个语法糖封装
