### ISSUE TITLE
"vue-amap": "^0.4.4" lazy-amap-api-loader.js 内不支持 扩展运算符 操作object 报错

### ISSUE THREAD

**Issue by Yibay** [ElemeFE/vue-amap#298]
"vue-amap": "^0.4.4" 版本，运行时报错：

./~/vue-amap/src/lib/services/lazy-amap-api-loader.js
。。。
You may need an appropriate loader to handle this file type.
|   constructor(config) {
|     this._config = {
|       ...DEFAULT_AMP_CONFIG,
|       ...config
|     };

说明：lazy-amap-api-loader.js 内不支持 扩展运算符 操作object 报错

因为是 node_modules内的文件，所以 应该是 由vue-amap 来处理，而不该是 引用 vue-amap的项目 来处理。

**Comment by jerry-i** [comment]
额为啥直接引源文件，`package.json` 指定 的入口是 `dist/index.js` 这个编译后的文件呢

**Comment by Yibay** [comment]
是的，使用 <el-amap> 时，import ElAmap from 'vue-amap/src/lib/components/amap' 了，后来读了源码，发现 <el-amap>，在 dist/index.js 中，注册为全局组件了。。。

**Comment by jerry-i** [comment]
引入源码，自己配置下babel-loader的路径规则
