### ISSUE TITLE
请问使用npm方式引入插件如何拿到AMapManager对象去操作地图？

### ISSUE THREAD

**Issue by gx0803** [ElemeFE/vue-amap#300]
```  
import { AMapManager } from 'vue-amap';
  import {Station} from '../service';
  //import {AlertModule} from 'vux';
  export default {
    components: {
      //AlertModule
    },
    data: function() {
      return {
        zoom: 12,
        center: [112.931467, 28.226765],
        AMapManager,
        markers: [],
        windows: [],
        source: 'click'
      };
    },
```
如上面的代码，目前使用import { AMapManager } from 'vue-amap这行代码可以正常的在template里面指定amapmanager对象，但是，如果我想在init以外的地方再去获取map对象进行个性化调整的时候，比如在mounted中进行ajax获取数据，然后加载ui组件实例化若干个simpleMarker的时候，就发现走不通了，如下：
```
            map=AMapManager.getMap();
            AMapUI.loadUI(['overlay/SimpleMarker'], function(SimpleMarker) {
              const marker = new SimpleMarker({
                iconLabel: 'A',
                iconStyle: 'red',
                map: map,
                position: map.getCenter()
              });
            });
```
这个时候控制台会报错：AMapManager.getMap is not a function，然而通过npm方式引入，并不能换使用示例中的代码：
let amapManager = new VueAMap.AMapManager();
这行代码也会报错，会提示VueAMap未定义！
请问在npm引入模式下，如果正确使用AMapManager？谢谢

**Comment by jerry-i** [comment]
https://elemefe.github.io/vue-amap/#/zh-cn/base/amap

请看示例

**Comment by gx0803** [comment]
@jerry-i 
谢谢，自己尝试出来了。
 let amapManager = new AMapManager();
使用npm的方式，直接这样new一个就行了，示例中没有写出来
