### ISSUE TITLE
引入失败

### ISSUE THREAD

**Issue by airzhanglin** [ElemeFE/vue-amap#309]
根据文档提供的方法在main.js引入出现__WEBPACK_IMPORTED_MODULE_3_vue_amp__.a.initAMapApiLoader is not a function错误

**Comment by jerry-i** [comment]
vue-amap 导出的是 umd 形式的，一般用webpack形式是已 commonjs 的形式，自己看下本地配置吧

**Comment by airzhanglin** [comment]
想用高德地图的实例获取cityCode .报错Cannot read property 'addressComponent' of undefined 有遇到这个问题吗

**Comment by Andyliwr** [comment]
@airzhanglin 同问

**Comment by airzhanglin** [comment]
@Andyliwr 在webpack.base.conf.js 中加入  externals: {
    'AMap': 'AMap'
  }
