### ISSUE TITLE
使用中出现疑难问题

### ISSUE THREAD

**Issue by gx0803** [ElemeFE/vue-amap#312]
1、该问题应该和插件本身无关，但想知道是否有优化方法。表现为在手机端使用高德地图的定位功能，使用浏览器定位（参考官方的Demo），具体代码如下
    //加载地图，调用浏览器定位服务
```
    map = new AMap.Map('container', {
        resizeEnable: true
    });
    map.plugin('AMap.Geolocation', function() {
        geolocation = new AMap.Geolocation({
            enableHighAccuracy: true,//是否使用高精度定位，默认:true
            timeout: 10000,          //超过10秒后停止定位，默认：无穷大
            buttonOffset: new AMap.Pixel(10, 20),//定位按钮与设置的停靠位置的偏移量，默认：Pixel(10, 20)
            zoomToAccuracy: true,      //定位成功后调整地图视野范围使定位位置及精度范围视野内可见，默认：false
            buttonPosition:'RB'
        });
        map.addControl(geolocation);
        geolocation.getCurrentPosition();
        AMap.event.addListener(geolocation, 'complete', onComplete);//返回定位信息
        AMap.event.addListener(geolocation, 'error', onError);      //返回定位出错信息
    });
```
使用该代码定位时，手机端会提示用户是否允许获取当前位置信息，而且每次重新加载地图页面时都会询问一次，不知道是否有办法只让该请求提示只出现一次？

2、第二个问题比较费解。因为在main.js中引入amap组件是全局的，所有用不到这个组件的页面访问时也会加载。所以现在想只在使用地图的界面中引入amap组件。比如station.js完整内容如下：
```
import Vue from 'vue'
import VueAMap from 'vue-amap';
Vue.use(VueAMap)
VueAMap.initAMapApiLoader({
  key: '8d40e5bb3b4c09fcef97dbc993cc5982',
  //plugin: ['AMap.Autocomplete', 'AMap.PlaceSearch', 'AMap.Scale', 'AMap.OverView', 'AMap.ToolBar', 'AMap.MapType', 'AMap.PolyEditor', 'AMap.CircleEditor','AMap.Driving','AMap.Geolocation'],
  plugin:['AMap.Geolocation'],
  uiVersion: '1.0' // UI库版本号
});
//var API_ROOT = "/data"
var API_ROOT = process.env.API_URL+"/data";
export const me = {
  getList(data){
    return Vue.http.post(API_ROOT + '/station/list',data);
  },
  getDetail(data){
    return Vue.http.post(API_ROOT + '/station/detail',data);
  }
}

```
然后在用到这个js的vue文件中，就能够顺利的在<script></script>片断使用如下代码
let amapManager = new AMapManager();
......
 export default {
   data: function() {
      return {
        viewType:'map',
        zoom: 10,
        center: [112.931467,28.226765],
        amapManager,
        events: {...}
   }
 }
}
当通过主界面上的一个按钮跳转到地图界面是正常的。但是进入页面后直接刷新或者跳转到别的界面然后使用手机的返回键返回该页面，或者直接在地址栏输入完整的路由地址直接访问这个页面时，会提示AMapUI is not defined，因为数据的ajax请求也是在AMapUI.loadUI()中进行的，UI组件未定义，所有的方法都不会执行了，不知道为什么会产生这个问题。

**Comment by AxeMea** [comment]
1 - 第一条高德原生行为，`vue-amap` 比较难改变

2 - `AMapUI is not defined` 出现这个问题，我较怀疑是高德 sdk 的脚本还没有加载好，你就执行了相应方法。两种方式，你可以尝试下。

* 将 `AMapUI.loadUI` 等逻辑放到 `el-amap` 的 `complete` event 中。
* 将逻辑放到 `loadPromise` 回调中。参看代码 
https://elemefe.github.io/vue-amap/#/zh-cn/introduction/ui-component

**Comment by gx0803** [comment]
@AxeMea 谢谢，一会就试试，请问一下events里面支持的事件有哪些，可以获取哪些参数，现在我只知道有init(map),还有complete，貌似complete拿不到map对象，这个事件绑定文档里似乎没有说明。

**Comment by AxeMea** [comment]
@gx0803 

可以参考文档。

https://elemefe.github.io/vue-amap/#/zh-cn/base/amap

**Comment by gx0803** [comment]
@AxeMea 已解决~~希望后续完善示例文档~~坚持把插件完善下去~
