### ISSUE TITLE
 Can not find callback: amapInitComponent, try define it before load JsApi!

### ISSUE THREAD

**Issue by datianjiao** [ElemeFE/vue-amap#315]
vue单页应用使用prerender-spa-plugin做seo的时候，做了一次预渲染，使用amap的时候报这个错。求个解决方案

**Comment by datianjiao** [comment]
已解决，修改HtmlWebpackPlugin的配置，把js插入到head中，vue改为手动挂载

**Comment by hy10021** [comment]
你好，目前我也出现这个问题，请教一下要如何修改配置
