### ISSUE TITLE
怎么才能在将center设置为当前位置，而不是把center写死

### ISSUE THREAD

**Issue by yellowlemmo** [ElemeFE/vue-amap#316]

**Comment by HengCC** [comment]
通过定位插件做. 官网文档有例子.

**Comment by yellowlemmo** [comment]
由于 Chrome 、IOS10 等已不再支持非安全域的浏览器定位请求，为保证定位成功率和精度，请尽快升级您的站点到 HTTPS 。
我使用了官方的定位插件了但是并没有实时定位，本地http站点怎么升级到https

**Comment by HengCC** [comment]
我本地是chrome最新版. macos 下的.  用的定位没问题.

**Comment by jerry-i** [comment]
@yellowlemmo 
https://elemefe.github.io/vue-amap/#/zh-cn/plugins/geolocation
