### ISSUE TITLE
[Feature Request] two way data binding

### ISSUE THREAD

**Issue by chikara-chan** [ElemeFE/vue-amap#319]
Hi, I'm a developer from America. I wanna write custom scale component. All of things works well,. But when zoom event triggered by gesture through amap kernel SDK, neither the value of attribute `zoom` nor `center` can be synchronized. I feel helpless but only the vue-amap support `.sync` modifier by itself.

**Comment by AxeMea** [comment]
😒😒

**Comment by chikara-chan** [comment]
嗨，我是来自美国的开发者。我想写自定义比例组件。所有的东西运作良好。但是当通过map内核SDK通过手势触发缩放事件时，属性zoom和center不能同步。我感到无奈，但只有vue-amap支持.sync修饰符本身。

---
Powered by Google Translate

**Comment by jerry-i** [comment]
Actually you can track `zoom` and `center`, by listening events like  `moveend`, `zoomchange`, etc of map instance. Hacking such events in `vue-amap` lib can be very Intrusive for the origin `Amap`
