### ISSUE TITLE
重新赋值改变marker的经纬度后，dragEnd事件失效

### ISSUE THREAD

**Issue by jack008** [ElemeFE/vue-amap#321]
正常版本：v0.1.6
出错版本：v0.4.5

默认展示的中心点，配置了可以拖动，一开始是可以拖动的，因为拖动结束有个回调，但是在手动定位后，也能标注出点并能拖动，但是dragEnd事件不执行了

**Comment by jerry-i** [comment]
手动是指的在代码里修改吗，我这边没有复现额，
https://elemefe.github.io/vue-amap/#/zh-cn/coverings/marker

**Comment by jerry-i** [comment]
old issue, no feedback. closed
