### ISSUE TITLE
折线的数据源问题,类似的包括点的position问题,Invalid Object: LngLat(NaN, NaN

### ISSUE THREAD

**Issue by HengCC** [ElemeFE/vue-amap#325]
官方的示例中提供给折线的数据是一个二维数组, 类似这样:

```js
let currentData = [[121.5389385, 31.21515044], [121.5389385, 31.29615044], [121.5273285, 31.21515044]],
```

然后组件的写法类似这样
```
<el-amap-polyline :path="currentData" />
```

我将地图的默认中心点设置成 currentData[0], 当上面的组件完成渲染后, currentData[0] 就会由一个数组变成一个对象.  这会导致组件再次重新渲染的时候 currentData[0]->Object , 转换成一个LngLat对象的时候就会出错. 

```
Error in callback for watcher "center": "Invalid Object: LngLat(NaN, NaN)"
```

我跟踪了下转换方法. 他接收的参数是一个数组. 而如果是一个对象就会出现错误.  我猜测可能是因为currentData 的引用被传递给了组件. 然后数据变更后这个引用所指的数据也发生了变更.

我想临时能解决的办法有2个.  

1. 自己写一个方法去计算center.  当是对象的时候自己重新计算
2. 深度克隆一个currentData 传递给组件.

但是我想官方是否可以在底层增加相应的支持.  比如地图原生需要的可能是对象数组. 那么将数据源就设置成对象数组而不是二维数组.

在或者是否可以在改动量较少的前提下增加内部的相应转换机制?

**Comment by HengCC** [comment]
或者最简单的设置一个计算属性. 地图内部的数据为

let inner_data = _.cloneDeep(currentData), 最终的目的就是不要改动传递进去的原始数据. 因为这些数据都是放在vuex中. 当地图在使用者不知道的前提下 变更了原始数据会导致这样的问题非常难以跟踪和解决.

**Comment by AxeMea** [comment]
是的，传进去的 `position` 会被转成一个对象，这种副作用是不友好的。

目前版本，仍然会有这样的问题，后续会对这层进行一个检测。

当前使用的话，可以做一层复制，避免副作用。

**Comment by wensiyuanseven** [comment]
这是对象引用地址问题吧
