### ISSUE TITLE
infow-window的bubble属性无效

### ISSUE THREAD

**Issue by 540240126** [ElemeFE/vue-amap#327]
你好，我发现在info-window上设置了bubble为true无效，通过查看源代码发现你们并没有写入bubble属性

**Comment by AxeMea** [comment]
`props` 中没有的话，暂时没有支持。可以考虑通过 `vue-amap` 拿到 `info-window` 的高德实例，然后设置上去。

**Comment by 540240126** [comment]
倒也不是因为这个，我是因为看到你们文档上写了这个属性但是代码里又没有😳

**Comment by AxeMea** [comment]
应该是疏漏了，欢迎 PR。😊

**Comment by 540240126** [comment]
不好意思, 我看了一下官方的文档infowindow是没有bubble这个属性的， 建议你们把文档中的去掉避免误导别人:smile:
