### ISSUE TITLE
在vue组件中，怎么在methods中方法调用定位获取当前位置信息啊

### ISSUE THREAD

**Issue by beanLau** [ElemeFE/vue-amap#328]
我看demo是这么写的，怎么在vue methods中调用0.getCurrentPosition方法？
<pre>
            loaded: false,
            plugin: [{
                pName: 'Geolocation',
                events: {
                    init(o) {
                        // o 是高德地图定位插件实例
                        o.getCurrentPosition((status, result) => {
                            alert(JSON.stringify(result))
                            if (result && result.position) {
                                self.guessCity = result.city;
                                self.$nextTick();
                            }
                        });
                    }
                }
            }]
</pre>

**Comment by AxeMea** [comment]
`o` 就是高德地图实例，你只要在 `methods` 中拿到地图实例，然后直接调用即可。
