### ISSUE TITLE
__WEBPACK_IMPORTED_MODULE_3_vue_amap___default.a.Marker is not a constructor

### ISSUE THREAD

**Issue by Agxr** [ElemeFE/vue-amap#329]
'events': {
          init (o) {
            var marker = new AMap.Marker({
              position: this.center
            })
            marker.setMap(o)
          }
        }
报错原因是什么？vue组件中使用events报错：__WEBPACK_IMPORTED_MODULE_3_vue_amap___default.a.Marker is not a constructor
谢谢

**Comment by AxeMea** [comment]
@Agxr 

你是不是 `import VMap from 'vue-amap'` 这样引入的。

换成这样 `VueAMap from 'vue-amap'`。

https://elemefe.github.io/vue-amap/#/zh-cn/introduction/compatible
