### ISSUE TITLE
跳转路由后  弹窗内地图不显示了

### ISSUE THREAD

**Issue by black-wt** [ElemeFE/vue-amap#330]
跳转路由后  弹窗内地图不显示了
求大神解答下啊

**Comment by AxeMea** [comment]
你好。

能描述地更为详细点。

**Comment by phoenix110** [comment]
我也遇到这个问题了。
再现：
1.进入一个页面，弹出地图对话框。
2.关闭地图对话框，跳转到其它页面。
3.再次进入有地图的页面，点开对话框，地图就不显示了。

**Comment by phoenix110** [comment]
和#334 很像。

**Comment by AxeMea** [comment]
是使用了 `transition` 吗？

可以参考下 #334

**Comment by phoenix110** [comment]
#334是两个地图切换，导致地图不显示。这个issue是在一个页面，也是由于transition得原因，导致地图不显示。
#334的对应方式在这里不管用呢。

**Comment by phoenix110** [comment]
最终结果还是设定本组件渲染时候，不进行缓存。
如果有其它方法，希望大家能够提供。
