### ISSUE TITLE
无法使用Geocoder 获得地址信息

### ISSUE THREAD

**Issue by airzhanglin** [ElemeFE/vue-amap#332]
在main.js里面
```
VueAMap.initAMapApiLoader({
  // 高德的key
  key: '*****',
  // 插件集合
  plugin: ['AMap.Autocomplete', 'AMap.PlaceSearch', 'AMap.Scale', 'AMap.OverView', 'AMap.ToolBar', 'AMap.MapType', 'AMap.PolyEditor', 'AMap.CircleEditor','AMap.Geocoder']
});
```
在组件里面使用
```
var geocoder = new AMap.Geocoder({
        radius: 1000,
        extensions: "all"
      });
      geocoder.getAddress([lng, lat], function(status, result) {
        if (status === "complete" && result.info === "OK") {
          if (result && result.regeocode) {
            self.address = result.regeocode.formattedAddress;
            self.$nextTick();
          }
        }
      });
```
出现 AMap.Geocoder is not a constructor 。

**Comment by AxeMea** [comment]
应该是高德还没有加载完成，就做了 `new AMap.Geocoder` 操作。你可以把这些逻辑放到 `Promise` 后，或者放到地图组件的 `init` event 中

**Comment by HF2018** [comment]
<el-amap ref="map"  vid="amapDemo" :amap-manager="amapManager" :center="center" :zoom="zoom" :plugin="plugin" :events="events" class="amap-demo" >

import VueAMap from "vue-amap";
import { lazyAMapApiLoaderInstance } from "vue-amap";
export default {
  name: "HelloWorld",
  data() {
    let self = this;
    return {
      amapManager:new VueAMap.AMapManager(),
      aa: [],
      address: "",
      zoom: 12,
      plugin: [
        "ToolBar",
        "Scale",
        "OverView",
        "Geocoder",
        {
          pName: "Geolocation",
        }
      ],
      center: [121.59996, 31.197646],
      events: {
        click: e => {
          this.center = [e.lnglat.lng, e.lnglat.lat];
          var geocoder = new VueAMap.Geocoder({
            radius: 1000,
            extensions: "all"
          });
          geocoder.getAddress([lng, lat], function(status, result) {
            if (status === "complete" && result.info === "OK") {
              if (result && result.regeocode) {
                self.address = result.regeocode.formattedAddress;
                self.$nextTick();
              }
            }
          });
        },
        init(o){
          
        },
      },

这样写的   也是在main.js中配置完成  结果还是出现 AMap.Geocoder is not a constructor

**Comment by Airlyonce** [comment]
请问解决了吗
我也遇到了同样的问题
