### ISSUE TITLE
在el-amap-marker（覆盖物的点坐标）中设置点击事件（@click）无效

### ISSUE THREAD

**Issue by zhangGuiF** [ElemeFE/vue-amap#335]
代码：
```
<el-amap  :center="center" :zoom="zoom" class="index_map" >
	 <el-amap-marker v-for="(marker, index) in markers"  :position="marker.position" 
	  	:vid="index" :key="index" :icon="marker.icon"  @click="toggleInfoWindow(marker,index)">
	  </el-amap-marker>
	  <el-amap-info-window   :position="infoWindowPos" :visible="infoWinOpen">
	 </el-amap-info-window>
</el-amap>`


`toggleInfoWindow: function(marker, idx) {
                   console.log(1111);
	            this._data.center = marker.position;//传递当前坐标作为中心值
	            this.infoWindowPos = marker.position; // 传递当前坐标
	            this.address = marker.infoText;// 传递当前坐标的地址
	            this.detail = marker.desc;
	            console.log(this);
	            if (this.currentMidx === idx) {
	            	this.infoWinOpen = !this.infoWinOpen;
	            } else {
	              this.infoWinOpen = true;
	              this.currentMidx = idx;
	            }
          	}
```

# `点击事件没反应@click="toggleInfoWindow(marker,index)"`

**Comment by AxeMea** [comment]
@zhangGuiF 

https://elemefe.github.io/vue-amap/#/zh-cn/coverings/marker

请查看 `events` 属性

**Comment by dodu2014** [comment]
@AxeMea  
https://elemefe.github.io/vue-amap/#/zh-cn/coverings/marker
无 events 属性呀, 
怎么设置 click 事件 ?

**Comment by chengtzu** [comment]
> @AxeMea https://elemefe.github.io/vue-amap/#/zh-cn/coverings/marker 无事件 属性呀， 怎么设置 单击 事件 ？

<el-amap-marker v-for="(marker, index) in markers" :key="index" :position="marker.position" @click="(e) => {clickArrayMarker(marker, e)}"></el-amap-marker>   文档里这样写的 无效呢

**Comment by Ycq428071** [comment]
<el-amap-marker
          ref="markers"
          v-for="(marker, index) in map.markers"
          :vid="index"
          :key="marker.index"
          :position="marker.position"
          :title="marker.address"
          :icon="marker.icon"
          :zIndex="marker.zIndex"
          **:events="marker.events"**
        />
      this.map.markers = data.positionList.map(item => {
        return {
          ...item,
          position: [item.longitude, item.latitude],
          zIndex: 100,
          icon: null,
          **events: {
            click() {
              console.log(111)
            }
          }**
        }
      })
这问题看了半天，这种可以
