### ISSUE TITLE
实例化的过程中报错//manager.setComponent is not a function

### ISSUE THREAD

**Issue by pythonyang6** [ElemeFE/vue-amap#338]
<img width="575" alt="1111" src="https://user-images.githubusercontent.com/32253938/35554007-21768820-05d5-11e8-8c45-8e6e85d9648d.png">

**Comment by sinchang** [comment]
至少得贴上自己的代码……

**Comment by jerry-i** [comment]
应该是manager的定义有问题，详见文档
