### ISSUE TITLE
如何在created生命周期中获取地图实例呢

### ISSUE THREAD

**Issue by MaBillion** [ElemeFE/vue-amap#341]
![image](https://user-images.githubusercontent.com/29347932/35679108-d6d018f0-0790-11e8-94dc-430d4e44e5fe.png)
输出null

**Comment by AxeMea** [comment]
由于地图实例初始化是异步的，所以推荐是在地图的 `init` 或者 `complete` event 中。

**Comment by AxeMea** [comment]
如果具体场景一定要在 created 中写，可以在 `created` 中 `$on`, 在 events 的 `init` 中 `$emit` 。
