### ISSUE TITLE
请问多个坐标，如何在地图内展示所有坐标并缩放具体的级别？

### ISSUE THREAD

**Issue by nonefirst** [ElemeFE/vue-amap#347]
## 问题
请问多个坐标，如何在地图内展示所有坐标并缩放具体的级别？
### VueAMap 版本
0.4.4
### OS/Browsers version
63.0.3239.84
### Vue 版本
2.5.13

**Comment by jerry-i** [comment]
这个只能使用命令式了，

`setFitView(overlayList:Array)`

记得在事件的回调里 track 下 center 和 z-index 的值

**Comment by nonefirst** [comment]
嗯~  我目前是使用的这种方式，获取原生amap对象，然后setFitView。
