### ISSUE TITLE
定位插件报错

### ISSUE THREAD

**Issue by lo6041** [ElemeFE/vue-amap#348]
## 问题
[Vue warn]: Failed to mount component: template or render function not defined.
### VueAMap 版本
"vue-amap": "^0.5.0",
### OS/Browsers version
win10专业版1709, 谷歌浏览器 63.0.3239.132（正式版本） （64 位）
### Vue 版本
"vue": "^2.5.2",
### 复现地址
本地开发

**Comment by jerry-i** [comment]
https://jsfiddle.net/9wL4eatk/
