### ISSUE TITLE
　geolocation插件 在iframe中，需要加入  allow:geolocation

### ISSUE THREAD

**Issue by dragoncn** [ElemeFE/vue-amap#349]
## 问题
浏览器控制台报警告： Geolocation access has been blocked because of a Feature Policy applied to the current document. See https://goo.gl/EuHzyv for more details.

### VueAMap 版本
0.5.0
### OS/Browsers version
win10 chrome 64
### Vue 版本
vue 2.5.13
### 预期
没有警告，能够获得当前地理定位 
### 实际
浏览器出现警告： Geolocation access has been blocked because of a Feature Policy applied to the current document. See https://goo.gl/EuHzyv for more details.

在回调函数中，查看返回的结果:
代码：
o.getCurrentPosition((status, result) => {
                  console.log('result'+Object.entries(result))

控制台中的结果：（由于　权限问题　定位失败）
resultmessage,Geolocation permission denied.,info,FAILED,status,0
## feature request

src\lib\patch\remote.js中，加入     ifrm.allow ="geolocation";

**Comment by jerry-i** [comment]
额，你是用的Chrome桌面版devtools里的iphone模拟调试的吧，线上暂时不会出现这问题，这段逻辑只会出现在非https的 ios设备打开的页面，safari暂时应该没有这种安全级别。节后会修的。
