### ISSUE TITLE
文档提供的范例，信息窗体 不能实现多个window间的切换，永远只能出第二个

### ISSUE THREAD

**Issue by flouda** [ElemeFE/vue-amap#353]
### VueAMap 版本
1.4.4
### OS/Browsers version
chrome 

### Vue 版本
vue 2.92
### 复现地址
https://elemefe.github.io/vue-amap/#/zh-cn/windows/info-window

### 预期
点对应的button出现各自的window

### 实际
点击第二个按钮，当count为2时，第二个window会出现，
点击第一个按钮，count=1，window2消失，但window1不会出现
![image](https://user-images.githubusercontent.com/3071113/36780497-2699019e-1cae-11e8-9e1a-1f137f00b670.png)

**Comment by AxeMea** [comment]
@flouda 

你好，这个地方确实有些问题。参考这里

https://elemefe.github.io/vue-amap/#/zh-cn/examples/windows/info-window

**Comment by AxeMea** [comment]
@flouda 

已修复。

https://elemefe.github.io/vue-amap/#/zh-cn/windows/info-window
