### ISSUE TITLE
调用海外地图需要加var map = new AMap.Map('container', {  gridMapForeign:true });怎么处理？

### ISSUE THREAD

**Issue by 17610172271** [ElemeFE/vue-amap#355]
var map = new AMap.Map('container', {
 gridMapForeign:true
});
怎么把gridMapForeign:true属性加进去？

**Comment by AxeMea** [comment]
高德 sdk 支持这个属性吗？

能把高德 `api` 中这个属性文档 `url` 发我下吗，我没有搜到。

**Comment by uhouzzui** [comment]
问题解决了么？

**Comment by iebb** [comment]
@AxeMea http://a.amap.com/lbs/static/pdf/%E6%B5%B7%E5%A4%96%E5%9C%B0%E5%9B%BEJS%20API%20%E8%B0%83%E7%94%A8%E8%AF%B4%E6%98%8E.pdf
