### ISSUE TITLE
兼容原生高德地图

### ISSUE THREAD

**Issue by ZY0118** [ElemeFE/vue-amap#358]
## 问题
![image](https://user-images.githubusercontent.com/20715943/36958373-3db4669a-2076-11e8-9a9a-1a62f025e2ef.png)
如此引入vue-amap，window里还是AMap这个名字的变量，一旦加载高德原生的文件，AMap就会被冲突掉了，不明白文档里说的引入VueAMap这样的名字就可以避免冲突指的是什么？有大神指点一二吗

**Comment by chenmingzeng** [comment]
就像你图中引入后 ，然后你就可以跟按照官方的方法来用，例如new AMap.LngLat();
