### ISSUE TITLE
安卓实体机地图资源问题

### ISSUE THREAD

**Issue by chenmingzeng** [ElemeFE/vue-amap#359]
## 问题
在安卓实体机中，地图加载完后，缩放后不会加载地图资源，连圆形和多边形的方法都失效
### VueAMap 版本
^0.5.2
### OS/Browsers version
Android7.1/微信浏览器、
QQ浏览器
### Vue 版本
^2.5.13
## feature request
![5689](https://user-images.githubusercontent.com/22519203/36967390-91122466-209a-11e8-9a22-2673cded72bf.jpg)

**Comment by jerry-i** [comment]
网络问题吧。我在微信里打开文档网站并没有挂😮

**Comment by chenmingzeng** [comment]
@jerry-i djui 但是我在苹果上又没问题~

**Comment by jerry-i** [comment]
network problems. closed
