### ISSUE TITLE
引入报错

### ISSUE THREAD

**Issue by Fzyfeng** [ElemeFE/vue-amap#371]
## 问题
 使用项目地图功能完全没有问题，但是项目载入时会出现下图的报错
### VueAMap 版本
0.5.3
### OS/Browsers version
chrome 最新
### Vue 版本
2.5.9
## feature request
希望得知原因，是否能屏蔽这些warn
![image](https://user-images.githubusercontent.com/23629370/37382513-3140f4fa-277e-11e8-8650-28ecf6b224d8.png)

**Comment by Fzyfeng** [comment]
by the way，I didn't use eleme-ui

**Comment by xinde** [comment]
同问

**Comment by jerry-i** [comment]
where are your codes?
