### ISSUE TITLE
如何实现移动端获取当前经纬度展现周边地址

### ISSUE THREAD

**Issue by 15521054523** [ElemeFE/vue-amap#375]
## 问题
如何实现移动端获取当前经纬度展现周边地址
### VueAMap 版本
无
### OS/Browsers version
无
### Vue 版本
xx
### 复现地址

**# 例如微信发朋友圈选择位置的时候，弹出的那个附近地址列表**

### 预期
无
### 实际
无

**Comment by AxeMea** [comment]
这个高德应该没有提供吧，最多提供了搜索某个经纬度周边的设施，比如美食等等。比如：

http://lbs.amap.com/api/javascript-api/example/poi-search/around-search
