### ISSUE TITLE
点坐标Marker使用本地icon资源

### ISSUE THREAD

**Issue by Symous** [ElemeFE/vue-amap#388]
marker的icon属性，如果使用本地资源时，并不像文档写的直接写入本地地址就可以，需要使用require引用，建议修复一下，以免误导新手。顺便问一下，如何手动设置icon的大小？

**Comment by jerry-i** [comment]
用 file-loader 或 url-loader 先 import 下

**Comment by houwhu** [comment]
> marker的icon属性，如果使用本地资源时，并不像文档写的直接写入本地地址就可以，需要使用require引用，建议修复一下，以免误导新手。顺便问一下，如何手动设置icon的大小？

同问？如何修改大小
