### ISSUE TITLE
请问要怎样添加浏览器定位服务插件AMap.Geolocation？

### ISSUE THREAD

**Issue by SanhongWong** [ElemeFE/vue-amap#39]
我想要在加载地图完成后，移动地图到定位地址。

**Comment by AxeMea** [comment]
@SanhongWong 

是否想得到类似下面这样的使用：

```
<el-amap address="上海真北路**号"></el-amap>
```

然后直接定位此地。

**Comment by SanhongWong** [comment]
@AxeMea 
不是，前面可能表达不清，其实就是地图定位，我需要借助浏览器定位来获取当前位置的地址信息（包括经纬度）。 效果像这样http://lbs.amap.com/api/javascript-api/example/location/browser-location/。
我尝试这样去引入定位创建，不过不行。
<pre>
<code>
    data () {
      return {
        loading: false,
        zoom: 16,
        amapManager: amapManager,
        plugins: [
          {
            pName: 'AMap.Geolocation',
            init (instance) {
              window.console.log(instance)
            }
          }
        ]
      }
    }
</code>
</pre>

**Comment by AxeMea** [comment]
@SanhongWong 

在`vue-amap`的文档中，暂时并没有`AMap.Geolocation`插件。

但并不代表不支持，只是觉得暂时不够友好，正在优化中。

如果现在需要使用，可以这样。

1. 全局引用插件

```
AMap.initAMapApiLoader({
  key: 'your code',
  plugin: [..., 'Geolocation']
});
```

2. 配置插件

```
data () {
      return {
        loading: false,
        zoom: 16,
        amapManager: amapManager,
        plugins: [
          {
            pName: 'Geolocation',
            events: {
               init (instance) {
                   // 手动调用定位
                   instance.getCurrentPosition()
                   window.console.log(instance)
               }
            }
          }
        ]
      }
    }
```

**Comment by SanhongWong** [comment]
@AxeMea 可以了，谢谢。我也应该多尝试的。Thanks

**Comment by SanhongWong** [comment]
@AxeMea plugin的events除init其他的事件好像没注册成功。
<pre>
<code>
      plugins: [
          {
            pName: 'Geolocation',
            enableHighAccuracy: true,
            timeout: 10000,
            zoomToAccuracy: true,
            buttonPosition: 'RB',
            events: {
              init (instance) {
                instance.getCurrentPosition()
                window.console.log(AMap.event)
              },
              complete (data) {
                window.console.log(data)
              },
              error () {
                window.console.log('error')
              }
            }
          },
          {
            pName: 'ToolBar',
            events: {
              init (instance) {
                window.console.log(instance)
              },
              zoomchanged (type) {
                window.console.log(type)
              }
            }
          }
        ]
</code>
</pre>
我本想是因为Geolocation是未来feature的原因，不过好像试了你们文档里面的ToolBar好像也不行。是不是src/lib/components/amap.vue里面166行有点问题？
<pre>
<code>
 165       for (let [k, v] of Object.entries(_plugin.events)) {
 166              if (k === 'init') return;
 167              AMap.event.addListener(this.$plugins[realPlugin.pName], k, v);
 168        }
</code>
</pre>
在判断是init的时候，应该是continue才对？

**Comment by AxeMea** [comment]
@SanhongWong 

谢谢反馈。请更新至 `0.1.5` 问题已修复。

**Comment by SanhongWong** [comment]
@AxeMea 0.1.5的还是不行，是不是最终编译的时候出了问题？还是用法改了？
我的代码还是
<code>  Vue.use(AMap)</code>
然后0.1.5下报错
<img src="https://cloud.githubusercontent.com/assets/11865626/22179291/4b263312-e08a-11e6-8339-1deef47a4193.png">
断点查看
<img src="https://cloud.githubusercontent.com/assets/11865626/22179310/a7fc4554-e08a-11e6-9b68-5edea7dab267.png">
对比0.1.4的断点
<img src="https://cloud.githubusercontent.com/assets/11865626/22179321/fe5de60a-e08a-11e6-8976-88a164d91743.png">

**Comment by jerry-i** [comment]
@SanhongWong 不好意思，更换了构建工具。已修复，更新到 v0.1.6

**Comment by SanhongWong** [comment]
thanks

**Comment by wengcd** [comment]
请问 `amapManager ` @AxeMea 如何引用

**Comment by jerry-i** [comment]
@wengcd 
```vue
<template>
    <el-amap vid="'amap-vue'" :map-manager="amapManager" >
    </el-amap>
</template>
<script>
import {AmapManger} from 'vue-amap';
const amapManger = new AmapManger();

export default {
  date() {
    return {
    amapMager: amapManger
    };
  }
};
</script>
```
