### ISSUE TITLE
报错t.amapManager.setMap is not a function

### ISSUE THREAD

**Issue by alan199355** [ElemeFE/vue-amap#396]
## 问题
初始化项目，按照教程来写，报错t.amapManager.setMap is not a function，地图也无法显示
### VueAMap 版本
0.5.4
### OS/Browsers version
Chrome 66
### Vue 版本
2.5.2
### 预期
正常显示
### 实际
![image](https://user-images.githubusercontent.com/6595339/39520673-286d03aa-4e3e-11e8-98ca-bc7c5ceffa65.png)

![image](https://user-images.githubusercontent.com/6595339/39520653-1bf422a2-4e3e-11e8-9481-26664c32b573.png)

![image](https://user-images.githubusercontent.com/6595339/39520728-51650564-4e3e-11e8-9b82-73ef74f752e1.png)

**Comment by Creamweiwei** [comment]
文档也不写清楚

**Comment by instrestedme** [comment]
import { AMapManager } from 'vue-amap'
let amapManager=new AMapManager()

...

export default {
 data () {
    return {
       amapManager
    }
  }
}
