### ISSUE TITLE
[feature request]el-amap-polygon 添加 draggable 属性

### ISSUE THREAD

**Issue by fourcels** [ElemeFE/vue-amap#399]
### VueAMap 版本
0.5.4

## feature request
el-amap-polygon 添加 draggable 属性

http://lbs.amap.com/api/javascript-api/reference/overlay#polygon

draggable | Boolean | 设置多边形是否可拖拽移动，默认为false

**Comment by AxeMea** [comment]
@fourcels 

欢迎 PR。😊

**Comment by AxeMea** [comment]
@fourcels 

`v0.5.6` 已经发布。
