### ISSUE TITLE
能单纯实现定位吗？

### ISSUE THREAD

**Issue by maidenkiller** [ElemeFE/vue-amap#401]
这个能单纯实现定位（获取经纬度）功能吗？

现在使用的时候必须在template里加一个隐藏不显示的el-amap，然后在plugin的init里o.getCurrentPosition获取位置。

能否单独调用方法即实现定位（获取经纬度）？

**Comment by AxeMea** [comment]
如果想单纯定位，可以考虑在 `lazyAMapApiLoaderInstance.load` 返回的 `Promise` 中，通过高德原生 `sdk` 来操作。

参考链接：
https://elemefe.github.io/vue-amap/#/zh-cn/introduction/init
http://lbs.amap.com/api/javascript-api/reference/location
