### ISSUE TITLE
如何在vue-amap中实现轨迹回放

### ISSUE THREAD

**Issue by feng9217** [ElemeFE/vue-amap#455]
## 问题
如何在 vue-amap 中实现轨迹回放呢?

## feature request
在文档中没有发现类似的功能说明
翻了翻高德的有对应的API: https://lbs.amap.com/api/javascript-api/example/marker/replaying-historical-running-data
不知道同功能在vue-amap中应该如何实现呢?

**Comment by junwei1114** [comment]
同样的问题

**Comment by icssoa** [comment]
moveAlong 在 init 中使用报错: a.Va is not a function

**Comment by 0undefined0** [comment]
同问

**Comment by passioncsu** [comment]
> moveAlong 在 init 中使用报错: a.Va is not a function

最后你怎么解决了? 通过引入官方UI的方式吗?

**Comment by feng9217** [comment]
通过引入官方的ui解决了
mounted() {
      lazyAMapApiLoaderInstance.load().then(() => {
        this.map = new AMap.Map('amap-container', {
          // center: [121.59996, 31.197646],
          zoom: 10,
        })
        var _this = this
        if(this.route_data.length > 0) {
          AMapUI.loadUI(['misc/PathSimplifier'], function(PathSimplifier) {
            if(!PathSimplifier.supportCanvas) {
              alert('当前环境不支持 Canvas！')
              return
            }
            _this.initPage(PathSimplifier)
          })
        }
      })
    },
