### ISSUE TITLE
正常vue-cli创建项目,惊现 jerryzhang

### ISSUE THREAD

**Issue by mactive** [ElemeFE/vue-amap#47]
<img width="735" alt="screenshot 2017-02-17 12 10 23" src="https://cloud.githubusercontent.com/assets/265410/23052173/29140940-f50a-11e6-9ac0-0e0e7e5a0c1c.png">
使用vue-cli 创建项目, 使用报错

```
// main.js
import Vue from 'vue'
import App from './App'
import AMap from 'vue-amap'
Vue.use(AMap)

// 初始化vue-amap
AMap.initAMapApiLoader({
  // 高德的key
  key: '3f3868abdb36336114bde5ab6eecdb68',
  // 插件集合
  plugin: ['AMap.Autocomplete', 'AMap.PlaceSearch', 'AMap.Scale', 'AMap.OverView', 'AMap.ToolBar', 'AMap.MapType', 'AMap.PolyEditor', 'AMap.CircleEditor']
})

new Vue({
  el: '#app',
  template: '<App/>',
  components: { App }
})
```

vue-amap 0.1.6 版本 dist/index.js 中 __vue_options__.__file 都是指向jerryzhang的目录
不知道是不是这个原因

**Comment by mactive** [comment]
会不会跟 更新 webpack 有关系 我看0.1.4 就没有  vue_options.__file 这个参数

**Comment by jerry-i** [comment]
现在还报这个错吗

**Comment by AxeMea** [comment]
真身出现，强势围观。

**Comment by mactive** [comment]
@jerry-i 不了,vue和相关的npm包升级了一下就好了. 谢谢
