### ISSUE TITLE
el-amap-marker   events

### ISSUE THREAD

**Issue by TTGitHub2017** [ElemeFE/vue-amap#471]
<el-amap-marker v-for="(marker, index) in markers" :position="marker.position" :events="marker.events" :visible="marker.visible" :draggable="marker.draggable" :vid="index"></el-amap-marker>
![image](https://user-images.githubusercontent.com/28435604/47898287-26b7f300-deb0-11e8-878a-a676d71f82da.png)

![image](https://user-images.githubusercontent.com/28435604/47898242-fa9c7200-deaf-11e8-9735-edfb6bdff653.png)

**Comment by zhujinyi** [comment]
不是事件吗？
