### ISSUE TITLE
加载点数量大于3000左右会奔溃

### ISSUE THREAD

**Issue by cn-Meepo** [ElemeFE/vue-amap#496]
当需要加载点比较多的时候会奔溃掉，原生高德没问题，文档上的点聚合大于3000点的时候也会很卡，大于10K的时候就会奔溃

**Comment by Skyofmine** [comment]
你时动态加载的点聚合吗？为什么我marker的init事件只触发一次啊，后面刷新数据都不触发init事件了

**Comment by bigbird231** [comment]
我用函数节流加载2986个点（每隔100毫秒加载400个点），其中2986个点中有6中图标。加载到第1600-2000个点的时候，渲染速度明显慢了很多，加载完2986个点之后，页面十分卡顿（单页应用），任何操作都十分卡顿。顺便问下，vue-amap是否集成了海量点？
----------------------------------
自问自答：vue-amap没有直接集成海量点，需要结合高德地图原生api进行使用。

看了高德地图的实现，发现点标记的实现方式真的很耗性能：
1.普通点标记都是用dom元素去添加的，这个底层实现方式本身就意味着点标记不能使用太多，基本上上百的点标记数据量（等量【甚至更多】的dom节点）就会影响性能；
2.海量点是将点标记一次性绘制在一张新的canvas上，再在地图图层上叠加这个canvas（为什么普通的点标记不用这种实现方式？）。

我在使用api过程中一直默认点标记已经是用canvas图层叠加的实现方式，而海量点是在普通点标记的基础之上进行事件和图形的抽稀优化。我建议，既然点标记是不断叠加dom元素，应该在文档上有所体现，让开发者知道普通点标记的性能损耗有多大，使用量应控制在二位数以内。当点超过二位数时，应该在文档中极力推荐使用海量点代替普通点标记。

另外，对于插件本身来说，不断叠加canvas图层也不是解决所有问题的方法，大众浏览器（移动端和PC端）的平均性能来说，在叠加到3层以及3层以上的canvas图层后，如果此时再对canvas内的图样进行交互操作，都会出现卡顿（对浏览器来说，同一片图形区域需要不断重绘这么多层画布）。建议任何叠加canvas的动作都控制在3层以内。

当然以上很多问题源于高德地图本身的实现，和vue-amap并没有太大责任，vue-amap只是对他进行了一层封装。

**Comment by Arisor** [comment]
大佬，官方的海量聚合是3w点不卡顿，我现在不到1w就卡死了，你的问题解决没

**Comment by txs1992** [comment]
这个和设计方案有关系

**Comment by xueshuai0922** [comment]
> ## 我用函数节流加载2986个点（每隔100毫秒加载400个点），其中2986个点中有6中图标。加载到第1600-2000个点的时候，渲染速度明显慢了很多，加载完2986个点之后，页面十分卡顿（单页应用），任何操作都十分卡顿。顺便问下，vue-amap是否集成了海量点？
> 自问自答：vue-amap没有直接集成海量点，需要结合高德地图原生api进行使用。
> 
> 看了高德地图的实现，发现点标记的实现方式真的很耗性能：
> 1.普通点标记都是用dom元素去添加的，这个底层实现方式本身就意味着点标记不能使用太多，基本上上百的点标记数据量（等量【甚至更多】的dom节点）就会影响性能；
> 2.海量点是将点标记一次性绘制在一张新的canvas上，再在地图图层上叠加这个canvas（为什么普通的点标记不用这种实现方式？）。
> 
> 我在使用api过程中一直默认点标记已经是用canvas图层叠加的实现方式，而海量点是在普通点标记的基础之上进行事件和图形的抽稀优化。我建议，既然点标记是不断叠加dom元素，应该在文档上有所体现，让开发者知道普通点标记的性能损耗有多大，使用量应控制在二位数以内。当点超过二位数时，应该在文档中极力推荐使用海量点代替普通点标记。
> 
> 另外，对于插件本身来说，不断叠加canvas图层也不是解决所有问题的方法，大众浏览器（移动端和PC端）的平均性能来说，在叠加到3层以及3层以上的canvas图层后，如果此时再对canvas内的图样进行交互操作，都会出现卡顿（对浏览器来说，同一片图形区域需要不断重绘这么多层画布）。建议任何叠加canvas的动作都控制在3层以内。
> 
> 当然以上很多问题源于高德地图本身的实现，和vue-amap并没有太大责任，vue-amap只是对他进行了一层封装。

普通点标记是不是可以看看Loca下的Layer 也是重新给个canvas
