### ISSUE TITLE
你好，我在定位插件那里配置click事件怎么无效啊？

### ISSUE THREAD

**Issue by guoguo250** [ElemeFE/vue-amap#504]
部份代码：let plugin = [{
					pName: 'Geolocation',
					events: {
						click(e) {
							alert(1);
						},
						init(o) {
							// o 是高德地图定位插件实例
							o.getCurrentPosition((status, result) => {
								if(result && result.position) {
									self.formattedAddress = result.formattedAddress;
									self.lng = result.position.lng;
									self.lat = result.position.lat;
									self.center = [self.lng, self.lat];
									self.loaded = true;
									//设置圆
									self.setCircles();
									//设置标记
									self.setMarkers();
									self.$nextTick();
								}
							});
						},

					}
				}]

源码这里是有添加事件监听的，if (k === 'init') v(pluginInstance);
            else AMap.event.addListener(pluginInstance, k, v); 想问下这里的click事件怎么无效啊，接下来我应该怎么做啊，我要做的功能是  我点击一下定位的小按钮，有事件回调，，谢谢哈

**Comment by guoguo250** [comment]
找到回调方法了

**Comment by yexiaodong** [comment]
回调方法怎样写？
