### ISSUE TITLE
根据文档引用还是不成功

### ISSUE THREAD

**Issue by Airlyonce** [ElemeFE/vue-amap#508]
按照文档下载并在在main.js中引入
Vue.use(VueAMap)

VueAMap.initAMapApiLoader({
  // 高德的key
  key: '我的key',
  // 插件集合
  plugin: ['AMap.Autocomplete', 'AMap.PlaceSearch', 'AMap.Scale', 'AMap.OverView', 'AMap.ToolBar', 'AMap.MapType', 'AMap.PolyEditor', 'AMap.CircleEditor'],
  // 高德 sdk 版本，默认为 1.4.4
  v: '1.4.4'
}); 
在组件中使用 el-amap 报错 

Unknown custom element: <el-amap> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by Airlyonce** [comment]
已解决

**Comment by carrypann** [comment]
遇到同样的问题，能否分享下如何解决的？

**Comment by guoshilin** [comment]
遇到同样的问题报错如下，请问是怎么解决的呢

[Vue warn]: Unknown custom element: <el-amap> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
