### ISSUE TITLE
[feat] Map Layer

### ISSUE THREAD

**Issue by Necmttn** [ElemeFE/vue-amap#51]
Is there any code examples or doc i can refer for it.

**Comment by AxeMea** [comment]
@Necmttn 

Like `AMap.TileLayer.Traffic` , ` AMap.ImageLayer` ?

We don't support these feature now. if you wanna it on latest version, you can do like these.

```
<el-amap :vid="'amap-vue'">
</el-amap>
```

```
export default {
  data() {
    return {
      events: {
        init(o) {
         // o is Gaode map instance
         // you can find it in
         // http://lbs.amap.com/api/javascript-api/example/layers/imagelayer
          var imageLayer = new AMap.ImageLayer(...);
          imageLayer.setMap(o);
        }  
      }  
    };
  }
}
```

**But we don't recommend you to use it by this way. if you need this feature, we can add it as soon as possible**

**Comment by Necmttn** [comment]
Yeah it would be great. let me know if is there anything i could help.

**Comment by Necmttn** [comment]
the main reason I needed map layers was I wanted to use http://lbs.amap.com/api/javascript-api/example/layers/satellite

but with toolbar plugin I have achieve my goal. It's also make it available traffic layer.  with almost zero config.

```
plugin: ['ToolBar', 'OverView', {
          pName: 'MapType',
          defaultType: 0,
        }],
```

**Comment by LabiKyo** [comment]
why is this issue closed? couldn't find any info about how to use a TileLayer.
