### ISSUE TITLE
在vue-amap 中如何使用  map.setFitView()； 的方法

### ISSUE THREAD

**Issue by virtueDe** [ElemeFE/vue-amap#516]
## 问题
**一列数据，用户选中一个数据，地图上添加一个标记，地图上展示的所有标记需要自适应在地图区域展现**

### VueAMap 版本
^0.5.9
### OS/Browsers version
Chrom 72.0.3626.119
### Vue 版本
2.5.11
### 预期
添加的几个标记自适应显示在地图区域
### 实际
不知道vue-amap 怎么使用  setFitView()  的方法

**Comment by virtueDe** [comment]
因为之前使用高德api 调用信息窗口的时候无法给信息窗口的节点绑定事件 ，所以用vue-amap来做，但是现在遇到了这个问题

**Comment by AxeMea** [comment]
https://elemefe.github.io/vue-amap/#/zh-cn/introduction/compatible

可以在 `init` event 中，获取高德实例，就可以直接调 setFitView 方法。

@virtueDe

**Comment by virtueDe** [comment]
@AxeMea  谢谢您的回复，问题已经解决

**Comment by HeWenKe** [comment]
@AxeMea 你这个怎么解决的,大佬,我也是需要这个适配当前地图内展示圆圈。

**Comment by shen-lan** [comment]
@HeWenKe  你解决了吗 
```
      events: {
        complete: () => {
          this.$refs.myMap.$amap.setFitView()
        },
      },
```
并无卵用

**Comment by Brick98** [comment]
已解决
https://www.jianshu.com/p/b34f585ba84a

**Comment by Brick98** [comment]
> @HeWenKe 你解决了吗
> 
> ```
>       events: {
>         complete: () => {
>           this.$refs.myMap.$amap.setFitView()
>         },
>       },
> ```
> 
> 并无卵用

https://www.jianshu.com/p/b34f585ba84a
