### ISSUE TITLE
slot click 无效

### ISSUE THREAD

**Issue by itwara** [ElemeFE/vue-amap#528]
[slots-渲染](https://elemefe.github.io/vue-amap/#/zh-cn/examples/coverings/marker-custom-content?id=slots-渲染) click事件无效

```
"vue": "^2.5.17",
"vue-amap": "^0.5.8"
```

**Comment by OlafCheng** [comment]
@itwara 我也遇到这个问题了, 请问你有解决办法吗?

**Comment by itwara** [comment]
冒泡到地图上处理，虽然不够优雅，但是也只能这样hack了
```
events: {
    click() {
        self.onMapClick()
    }
 }
```
