### ISSUE TITLE
extdata 的setExtData(ext:Any)和getExtData( )可以添加吗？

### ISSUE THREAD

**Issue by liuwei1207** [ElemeFE/vue-amap#55]
项目需要一些自定义数据挂载到marker点上， 一些高的地图的api似乎并没有全部提供出来。

**Comment by liuwei1207** [comment]
好吧。。我已经解决了。 你们的文档太简单了。。。demo太少了。  我是看你们源码找到的解决方法。 不过还是谢谢， 这个项目很不错！

**Comment by LabiKyo** [comment]
怎么解决的，通过init方法调用么

**Comment by pandaljf** [comment]
我也想知道，求教 @liuwei1207
