### ISSUE TITLE
<el-amap> 组件无效

### ISSUE THREAD

**Issue by liuzeWeb** [ElemeFE/vue-amap#558]
前端使用 quasar 框架 引用vue-amap 报：

Unknown custom element: <el-amap> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by loongw513029** [comment]
> 前端使用 quasar 框架 引用vue-amap 报：
> 
> Unknown custom element: - did you register the component correctly? For recursive components, make sure to provide the "name" option.

请问你是怎么解决的
