### ISSUE TITLE
polygon editable

### ISSUE THREAD

**Issue by Raistlin916** [ElemeFE/vue-amap#57]
![wechatimg2](https://cloud.githubusercontent.com/assets/2560402/23536466/048360d4-0000-11e7-8ae2-075858d5fbf7.jpeg)

在移动端需要使用可编辑的多边形时，拖动的圆按钮太小了，很容易误操作。在安卓上体验尤其糟糕。

可以提供一个控制按钮大小的参数吗？类似于 editorBtnRadius

**Comment by jerry-i** [comment]
这边我是封装了高德的 [AMap.PolyEditor](http://lbs.amap.com/api/javascript-api/reference/plugin#AMap.PolyEditor) 插件
但是貌似高德自己都没有提供这样的功能，可能没有兼顾移动端吧。
可以去 [论坛](http://lbsbbs.amap.com/forum.php?mod=forumdisplay&fid=40)提需求。

**Comment by Raistlin916** [comment]
😔
