### ISSUE TITLE
el-amap-marker 组件 label 属性首次更新未同步到视图

### ISSUE THREAD

**Issue by ekoooo** [ElemeFE/vue-amap#573]
## 问题
`el-amap-marker` 组件 `label` 属性首次更新无效

### VueAMap 版本
`^0.5.10`

### OS/Browsers version
`macOS Mojave 10.14.5 (18F132)`/`Google Chrome 77.0.3865.90（正式版本）（64 位）`

### Vue 版本
`^2.6.10`

### 复现地址
[https://jsfiddle.net/omx7a4fc/3/](https://jsfiddle.net/omx7a4fc/3/)

### 预期
当 `el-amap-marker` 组件 `label` 属性首次更新时视图应同步更新

### 实际
当 `el-amap-marker` 组件 `label` 属性首次更新时**未**视图同步更新

## feature request
无

**Comment by BeHappyWsz** [comment]
试了一圈，把**版本提高**就可以了。
才想到之前也遇到了类似的问题，marker事件click中需要更换label，使用了**原生的setLabel()**才可以。后来把版本跟上来就正常了。
![image](https://user-images.githubusercontent.com/32267661/66976073-1e61c380-f0d3-11e9-88a4-c1eab04a38fc.png)

**Comment by ekoooo** [comment]
> 试了一圈，把**版本提高**就可以了。
> 才想到之前也遇到了类似的问题，marker事件click中需要更换label，使用了**原生的setLabel()**才可以。后来把版本跟上来就正常了。
> ![image](https://user-images.githubusercontent.com/32267661/66976073-1e61c380-f0d3-11e9-88a4-c1eab04a38fc.png)

感谢，问题解决了！

**Comment by ricekyan** [comment]
content-render 属性渲染的template 本地测试能正常显示，但是打包部署后，就不能正常显示了；

**Comment by ricekyan** [comment]
axios({
          method: 'get',
          url: '/api/Robots'
        }).then(res => {
          let data = res.data
          this.center = [data[0].geo.lng, data[0].geo.lat]
          this.componentsMarkers = data.map((item, index) => {
            return {
              position: [item.geo.lng, item.geo.lat],
              vid: `${index}`,
              contentRender: h =>
                h(BtnComponent, {
                  props: {
                    text: `${item.name}`,
                    src: require('../../static/images/robot/gate-online.png')
                  },
                  style: {
                    // background: '#ffbf60',
                    color: '#fff'
                  },
                  nativeOn: {
                    click: () => this.handler(item.id)
                  }
                })
            }
          })
        })

**Comment by ricekyan** [comment]
@BeHappyWsz

**Comment by ricekyan** [comment]
<el-amap-marker
        v-for="(marker, index) in componentsMarkers"
        :key="index"
        :position="marker.position"
        :vid="marker.vid"
        :content-render="marker.contentRender"
      ></el-amap-marker>

**Comment by ricekyan** [comment]
> ```
> axios({
>       method: 'get',
>       url: '/api/Robots'
>     }).then(res => {
>       let data = res.data
>       this.center = [data[0].geo.lng, data[0].geo.lat]
>       this.componentsMarkers = data.map((item, index) => {
>         return {
>           position: [item.geo.lng, item.geo.lat],
>           vid: `${index}`,
>           contentRender: h =>
>             h(BtnComponent, {
>               props: {
>                 text: `${item.name}`,
>                 src: require('../../static/images/robot/gate-online.png')
>               },
>               style: {
>                 // background: '#ffbf60',
>                 color: '#fff'
>               },
>               nativeOn: {
>                 click: () => this.handler(item.id)
>               }
>             })
>         }
>       })
>     })
> ```

打包后 ，浏览器也未正常显示该标签，<div class="amap-marker" style="top: 72px; left: -87px; z-index: 100; transform: rotate(0deg); transform-origin: 9px 31px; display: block;"><div class="amap-marker-content" style="opacity: 1;"></div></div>

**Comment by ricekyan** [comment]
<div class="amap-marker" style="top: 72px; left: -87px; z-index: 100; transform: rotate(0deg); transform-origin: 9px 31px; display: block;"><div class="amap-marker-content" style="opacity: 1;"></div></div>

**Comment by ricekyan** [comment]
```<div class="amap-marker" style="top: 72px; left: -87px; z-index: 100; transform: rotate(0deg); transform-origin: 9px 31px; display: block;"><div class="amap-marker-content" style="opacity: 1;"><!--function(t,n,i,r){return dn(e,t,n,i,r,!0)}--></div></div>```

**Comment by BeHappyWsz** [comment]
> `<div class="amap-marker" style="top: 72px; left: -87px; z-index: 100; transform: rotate(0deg); transform-origin: 9px 31px; display: block;"><div class="amap-marker-content" style="opacity: 1;"><!--function(t,n,i,r){return dn(e,t,n,i,r,!0)}--></div></div>`

还没用过**contentRender**。VNode render渲染机制需要v0.4.3以上，应该也有吧。
先排查一下：
1. 打包过程看有没异常
2. 浏览器中看渲染的过程有没异常报错
3.上面的html咋还有注释掉的function。部署后没正常渲染，就看环境是否异常。
