### ISSUE TITLE
Mouse Tool [Feature Request]

### ISSUE THREAD

**Issue by Necmttn** [ElemeFE/vue-amap#58]
Currently we can use mouse tool for calculate area, calculate distance. but when we want to create polygon or polyline it won't create Vue instance for that element. so we don't have any control on it. 

It would be great do if mouse tool Draw() function create's Vue instance of that element. 

any thoughts about it ?

**Comment by AxeMea** [comment]
@Necmttn 

 >> "but when we want to create polygon or polyline it won't create Vue instance for that element."

HI, I don't understand the meaning. can you give me some demo? Thx.

**Comment by Necmttn** [comment]
I will do it tomorrow  ! 🤓

**Comment by jerry-i** [comment]
@Necmttn you  can just use mouse tool Draw() to  at  callback  function get data of polygon for example. then use this data to render a  Vue instance of that element.
