### ISSUE TITLE
4g 下定位Get geolocation time out.get iplocation failed 

### ISSUE THREAD

**Issue by djkdeveloper** [ElemeFE/vue-amap#595]
作者我看这个问题之前有人提过，回答是高德的问题，但是我感觉应该不是，场景是这样的
4g 情况下：我有个首页 ，然后进入附近店铺页面定位当前经纬度这时候报错说是Get geolocation time out.get iplocation failed  但是注意，这时候我直接刷新当前附近店铺页面 ，不从首页进去这时候是可以定位成功的
wift 情况下： 首页进去到附近店铺页面然后获得的经纬度是有偏差的不准确，但是我在附近店铺页面直接刷新经纬度 获得的经纬度是基本精确的

**Comment by web-farmer** [comment]
解决了吗？

**Comment by acongy** [comment]
解决了吗
