### ISSUE TITLE
在微信开发工具下报错 

### ISSUE THREAD

**Issue by dengdan99** [ElemeFE/vue-amap#62]
在微信开发工具下报错： （对运行没有影响）
Unhandled promise rejection TypeError: Object.entries is not a function
但 chrome 模拟下没有报错

经过测试 

```
data () {
    var self = this
    return {
      plugin: [{
        pName: 'CitySearch',
        events: {
          init (o) {
            o.getLocalCity((status, result) => {
....

```
貌似 微信不支持 Object.entries 何解呢

**Comment by AxeMea** [comment]
咦， `Babel` 转了应该没问题吧。

**Comment by kusion** [comment]
我也出现过这情况，是在钉钉H5开发，估计钉钉所依赖的浏览器内核版本过低，不支持ES6特性造成的。还有微信开发工具，貌似是用nw.js做的吧，按道理来讲，nw.js封装的浏览器内核，应该也不会太过于陈旧吧！

**Comment by AxeMea** [comment]
@kusion @dengdan99 

你好，更新到 `vue-amap@0.2.0` 试一下。
