### ISSUE TITLE
ncaught (in promise) TypeError

### ISSUE THREAD

**Issue by liushuojia** [ElemeFE/vue-amap#627]

**Comment by liushuojia** [comment]
抱歉按错了， 顺便把问题说下， 页面刷新时候有时候地图无法正常定位， 
刷新无法显示地图已经使用大神的方法
const amapKeys = Object.keys(localStorage).filter((key) => key.match(/^_AMap_/))
amapKeys.forEach((key) => {
  // console.log(key)
  localStorage.removeItem(key)
})
清理了， 地图可以正常显示， 但是地图的地理位置无法正确定位到， 应该是异步获取数据没有处理完毕， 直接执行定位导致的

**Comment by zxy16621195304** [comment]
兄弟解决了吗
