### ISSUE TITLE
Search-Box 问题

### ISSUE THREAD

**Issue by wpf1994** [ElemeFE/vue-amap#63]
@AxeMea
系统：win10
浏览器：chrome 56.0.2924.87
vue-amap: 0.1.7

## 问题
1、不知道为何在电脑上的chrome浏览器无法定位（已经设置允许定位），但是手机中的却可以
![image](https://cloud.githubusercontent.com/assets/10007650/23838451/c36ce466-07d0-11e7-8d65-92d1db3d2c8b.png)
2、我的search-box 输入内容没有补充提示
3、点击搜索老是如下图
![image](https://cloud.githubusercontent.com/assets/10007650/23838453/d00260f2-07d0-11e7-944f-1b2390387c74.png)

**Comment by AxeMea** [comment]
@wpf1994 

你好。

#### 1 - 浏览器无法定位

如果你手机和 PC 连的是一个网络的话，手机可以电脑不行，那和网络应该没关系。现在看起来，那很可能是和系统有关，这边测试用的 `Chrome` 版本和你一样的，只是系统是 `OS X`。

#### 2 - `pois` 报错问题

可以看下最新的文档里面的示例代码，由于某些搜索关键词，搜索不到定位，`pois` 为空，会引起这个报错，所以多了一个判断。你可以这么修改下，再看下是否 OK 。

```javascript

...

if (pois.length > 0) {
  ...
}

...

```

**Comment by wpf1994** [comment]
@AxeMea 
文档地址我看的这个 https://elemefe.github.io
## 1、定位问题
那我待会验证下是不是系统问题，再回复你
## 2、pois 问题
还是失败的
![image](https://cloud.githubusercontent.com/assets/10007650/23840293/0fa4a5ae-07df-11e7-98cc-eb91e1df0a01.png)
## 3、搜索关键字提示的这个怎么配置啊，我看的文档没有

**Comment by AxeMea** [comment]
@wpf1994 

你好。

能贴较完整的代码吗？也方便更好帮助你查找问题。

^_^

**Comment by wpf1994** [comment]
@AxeMea 
我把相关的都贴出来了，非常感谢你
## html
![image](https://cloud.githubusercontent.com/assets/10007650/23855344/41f96d7c-0830-11e7-9c5a-14ecf5de72c9.png)

## js data
![image](https://cloud.githubusercontent.com/assets/10007650/23855673/94e3ffec-0831-11e7-97eb-0dcd37ab751e.png)

## js methods
![image](https://cloud.githubusercontent.com/assets/10007650/23855699/ad6465ca-0831-11e7-95ca-cb020a2587c9.png)

**Comment by AxeMea** [comment]
@wpf1994 

看代码应该没啥问题。

你加下 `vue-amap` 的客服群，在那个里面沟通。

![image](https://cloud.githubusercontent.com/assets/4532661/23931178/d759bff2-096b-11e7-8f28-49ec482fee30.png)

**Comment by wpf1994** [comment]
@AxeMea 
你好，这个二维码是过期的哎( ▼-▼ )

**Comment by AxeMea** [comment]
@wpf1994 

![image](https://cloud.githubusercontent.com/assets/4532661/23931681/4c5d459c-096e-11e7-8168-11baddce9802.png)
