### ISSUE TITLE
使用el-amap-marker报错 The data property "position" is already declared as a prop. Use prop default value instead.

### ISSUE THREAD

**Issue by WishMelz** [ElemeFE/vue-amap#635]
## 问题
使用el-amap-marker报错 The data property "position" is already declared as a prop. Use prop default value instead.
但是地图会显示出来，这个标记点也会显示出来。就单纯控制台报错
### VueAMap 版本
0.5.10
### OS/Browsers version
win10 家庭版 64位
### Vue 版本
2.5.17

**Comment by sun-weitao** [comment]
postion 用数组传参
