### ISSUE TITLE
[searchbox] 搜索最多返回 10 个结果

### ISSUE THREAD

**Issue by thREam** [ElemeFE/vue-amap#65]
RT, 事实上是有更多的搜索结果, 但只返回了 10 个.

谢谢

**Comment by AxeMea** [comment]
@thREam 

你好。

`vue-amap` 是基于高德的，然后高德有这样的约束。
![image](https://cloud.githubusercontent.com/assets/4532661/23854668/63dd4d62-082d-11e7-8a3c-ac7c161c4945.png)

http://lbs.amap.com/api/javascript-api/reference/search#m_AutocompleteResult

有些无奈。

**Comment by thREam** [comment]
@AxeMea 
谢谢你的回复, 不好意思, 可能我描述的不太清楚.
我所提到的问题, 不是 `autoComplete`, 是 `onSearchResult`, 对应的是 `ampa-search-box.vue` 的如下代码:
```
    search() {
      this.tips = [];
      this._placeSearch.search(this.keyword, (status, result) => {
        let {poiList: {pois}} = result;
        let LngLats = pois.map(poi => ({lat: poi.location.lat, lng: poi.location.lng}));
        this._onSearchResult(LngLats);
      });
    }
```
此处使用的是 [AMap.PlaceSearch](http://lbs.amap.com/api/javascript-api/reference/search#m_AMap.PlaceSearch), 是支持翻页的(`pageSize`, `pageIndex`).

**Comment by AxeMea** [comment]
@thREam 

请升级到 `vue-amap@0.2.0`

你好，文档已经更新。 

通过 `init` 事件将 `PlaceSearch` 的实例暴露出来了。你可以调用 `o.placeSearch.setPageSize()` 这样的高德 sdk 来满足你的需求。

**Comment by jerry-i** [comment]
@thREam  `searchOption` 可以设置该属性参见    [PlaceSearchOptions](http://lbs.amap.com/api/javascript-api/reference/search#m_PlaceSearchOptions)

**Comment by he5050** [comment]
@jerry-i  怎么设置 事件监听？
``` javascript
init: ({ autoComplete, placeSearch }) => {
          console.log(placeSearch.getLang());
          AMap.event.addListener(autoComplete, "select", e => {
            this.$emit("select", e.poi);
          });
          AMap.event.addListener(placeSearch, "complete", e => {
            this.$emit("select", e.poi);
          });
        }
```
