### ISSUE TITLE
文档写的不是太清晰

### ISSUE THREAD

**Issue by youngchen1987** [ElemeFE/vue-amap#68]
参考vue百度的:https://dafrok.github.io/vue-baidu-map

**Comment by AxeMea** [comment]
@youngchen1987 

你好。

谢谢你的建议。

`vue-amap` 文档的更新计划已经启动。

**Comment by HiZhaoxiaoyang** [comment]
package是能装，但任何npm run不起来，看了文档有示例也不是完备的。也许作者觉得直接npm run太简单了吧，开发者得有node环境调试基础自行解决

**Comment by AxeMea** [comment]
@youngchen1987 

你好，已经对文档进行了更新。后续会围绕「示例中心」，不断完善。欢迎提 issue。

**Comment by youngchen1987** [comment]
好的
