### ISSUE TITLE
信息窗体问题二三

### ISSUE THREAD

**Issue by colinyao** [ElemeFE/vue-amap#69]
1、信息窗体对象是个数组，是可以同时传入多个窗体对象吗，可是我同时初始化两个以后页面就没有显示了，也不报错，所以我在切换时，是应该一直修改窗体内容，还是创建多个窗体，控制显示隐藏？
2、窗体怎么控制显示隐藏，我动态清空windows再push一个新窗口可以实现切换，但是手动关闭窗体以后，我再怎么修改windows数组，窗体都不再显示了，所以是那里操作错误？
最后能提供一个窗体切换控制的demo吗，感激不敬！

**Comment by jerry-i** [comment]
如果窗体和marker有联动可以用事件去控制。最近太忙了，改天总结下

**Comment by HbuJiaTian** [comment]
手动关闭信息窗体之后，如果才能重新显示窗体呢，这个问题现在有进展了吗？

**Comment by rossroma** [comment]
我也遇到这个问题了，窗体手动关闭后，如何再打开一个？ @HbuJiaTian  你有进展了吗？

**Comment by HbuJiaTian** [comment]
没有呢，这个框架好像实现不了这个，等待大神解释@rossroma

**Comment by huangyanxiong01** [comment]
@colinyao 能同时画出多个窗体吗，windows有四个元素结果只显示一个

**Comment by AxeMea** [comment]
@colinyao @HbuJiaTian @rossroma @huangyanxiong01 

https://elemefe.github.io/vue-amap/#/zh-cn/examples/windows/info-window
