### ISSUE TITLE
searchBox无法使用

### ISSUE THREAD

**Issue by MrSuperJ** [ElemeFE/vue-amap#71]
Error in beforeCreate hook: 
(found in <ElAmapSearchBox> at /Users/jerryzhang/workProject/vue-amap/src/lib/components/amap-search-box.vue)
不清楚在哪里修改这个路径

**Comment by AxeMea** [comment]
@MrSuperJ 

你好，请问你用的版本是？

**Comment by MrSuperJ** [comment]
"version": "0.2.1"

**Comment by AxeMea** [comment]
@jerry-i 

查下问题，你又惊现了。
