### ISSUE TITLE
我怎么通过点击地图获取到此点的详细地址（我只看如何获取到此点的经纬度）

### ISSUE THREAD

**Issue by xuxiaolong1029** [ElemeFE/vue-amap#73]

**Comment by jerry-i** [comment]
这个可能要用到搜索服务

**Comment by AxeMea** [comment]
@xuxiaolong1029 

可以这样。

```javascript
export default {
  data: function() {
    return {
      events: {
        click(e) {
          console.log('lng: ' + e. lnglat.lng);
          console.log('lat: ' + e. lnglat.lat);
        }
      }
    };
  }
}
```

**Comment by xuxiaolong1029** [comment]
这个我知道，我们的业务需求需要我们点击地图之后获取到此点经纬度和详细地址。
plugin: [{
                    pName: 'Geolocation',
                    showMarker:true,
                    events: {
                        init(o) {
                            o.getCurrentPosition((status, result) => {
                                self.center = [result.position.lng, result.position.lat];
                                this.editForm.stlc = result.formattedAddress
                            });
                        }
                    }
                }]
这个定位插件只能是初始化的时候获取到你所在地点的详细地址，没有点击事件。高德地图中做的挺好的，希望我们的vue-amap也能把这个功能添加上

**Comment by AxeMea** [comment]
@xuxiaolong1029 

明白你的需求了。

^_^

**Comment by xuxiaolong1029** [comment]
嗯嗯，谢谢 我一直会关注你们vue-amap的

**Comment by AxeMea** [comment]
@xuxiaolong1029 

如果现在需要满足你们的业务需求。

你可以通过 `amap` 的 `click`事件拿到坐标后，接着用高德的方式来玩。

http://lbs.amap.com/api/javascript-api/example/geocoder/regeocoding

**Comment by jerry-i** [comment]
提供个思路，将搜索封装成一个服务（最好将callback promise化）， 入参是经纬度

**Comment by Tiramisu1** [comment]
> 这个我知道，我们的业务需求需要我们点击地图之后获取到此点经纬度和详细地址。
> plugin: [{
> pName: 'Geolocation',
> showMarker:true,
> events: {
> init(o) {
> o.getCurrentPosition((status, result) => {
> self.center = [result.position.lng, result.position.lat];
> this.editForm.stlc = result.formattedAddress
> });
> }
> }
> }]
> 这个定位插件只能是初始化的时候获取到你所在地点的详细地址，没有点击事件。高德地图中做的挺好的，希望我们的vue-amap也能把这个功能添加上

你好！ 我想获取当前所在地的城市名称 但是我打印result里面并没有formattedAddress这个参数呢

**Comment by liuboaibc** [comment]
点击获取经纬度之后，可利用逆地理编码，获取详细地址
```
AMap.plugin('AMap.Geocoder', function() {
  var geocoder = new AMap.Geocoder({
    // city 指定进行编码查询的城市，支持传入城市名、adcode 和 citycode
    city: '010'
  })
 
  var lnglat = [116.396574, 39.992706]

  geocoder.getAddress(lnglat, function(status, result) {
    if (status === 'complete' && result.info === 'OK') {
        // result为对应的地理位置详细信息
    }
  })
})
```
