### ISSUE TITLE
升级到最新版本0.2.2，地图都显示不了了，样式高度设置不了

### ISSUE THREAD

**Issue by chunecai** [ElemeFE/vue-amap#76]
用来文档中的demo：
<template>
  <div class="amap-page-container">
    <el-amap :vid="'amap-vue'" :center="center" :zoom="zoom" :map-manager="amapManager" :plugin="plugin" :events="events">
       <el-amap-marker v-for="marker in markers" :position="marker"></el-amap-marker>
    </el-amap>
    <button v-on:click="getMap">get map</button>
    <button type="button" name="button" v-on:click="addZoom">zoom++</button>
    <button type="button" name="button" v-on:click="subZoom">zoom--</button>
    <button type="button" name="button" v-on:click="changeCenter">change center</button>
  </div>
</template>
<script>
import { AMapManager } from 'vue-amap';
let amapManager = new AMapManager();
export default {
  name: 'amap-page',
  data: function() {
    return {
      vid: 'amap-vue-1',
      zoom: 12,
      center: [121.59996, 31.197646],
      events: {
        'moveend': () => {
          let mapCenter = this.amapManager.getMap().getCenter();
          this.center = [mapCenter.getLng(), mapCenter.getLat()];
        },
        'zoomchange': () => {
          this.zoom = this.amapManager.getMap().getZoom();
        },
        'click': (e) => {
          alert('map clicked');
        }
      },
      plugin: ['ToolBar', {
        pName: 'MapType',
        defaultType: 0,
        events: {
          init(o) {
            console.log(o);
          }
        }
      }],
      amapManager: amapManager,
      markers: [
               [121.59996, 31.197646],
               [121.40018, 31.197622],
               [121.69991, 31.207649]]
    };
  },
  methods: {
    getMap: function() {
      console.log(this.amapManager.getMap());
      console.log(this.center);
    },
    addMarker: function() {
      let lng = 121.5 + Math.round(Math.random() * 1000) / 10000;
      let lat = 31.197646 + Math.round(Math.random() * 500) / 10000;
      this.markers.push([lng, lat]);
    },
    addZoom() {
      this.zoom++;
    },
    subZoom() {
      this.zoom--;
    },
    changeCenter() {
      this.center = [this.center[0] + 0.1, this.center[1] + 0.1];
      console.log(this.center);
    }
  }
};
</script>

显示空白的，高度是0.
需要在这里设置，但是写了css也没有用。

![Uploading image.png…]()
![Uploading image.png…]()
![Uploading 1460894437_832577.png…]()

**Comment by AxeMea** [comment]
@chunecai 

抱歉，请升级至 `vue-amap@0.2.3`。

**Comment by chunecai** [comment]
可以显示了，升级到0.2.3版本。 非常感谢。

**Comment by chunecai** [comment]
需要设置高度才可以显示：
.amap-page-container{
  height:1000px
}
.amap-container {
    height: 300px!important
}

**Comment by AxeMea** [comment]
@jerry-i

**Comment by jerry-i** [comment]
@chunecai O__O "… 最外面的容器高度要自己设置， 我只加了 `.el-vue-amap-container,.el-vue-amap-container .el-vue-amap{height:100%}`

**Comment by chunecai** [comment]
好的，知道了。 3Q
