### ISSUE TITLE
[Vue warn]: Property or method "amap" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 

### ISSUE THREAD

**Issue by zpyas** [ElemeFE/vue-amap#77]
Hi,
  我是用vue init出来的项目，按照官方文档上修改了main.js文件
![mainjs](https://cloud.githubusercontent.com/assets/8863179/24414710/c0f9e312-1411-11e7-8117-cefcb36a5f96.png)

还有Map的文件
![amap](https://cloud.githubusercontent.com/assets/8863179/24414678/ad566b50-1411-11e7-8af0-f724f324eee0.png)

编译的时候没有问题，打开页面后出现了
[Vue warn]: Property or method "amap" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
这个提示

版本如下：
"vue": "^2.2.2",
"vue-amap": "^0.2.3",
"vue-router": "^2.2.0"

想问一下，是我哪个地方设置不正确么？
谢谢

**Comment by jerry-i** [comment]
@zpyas  你在组件上设置了属性`amap-vue`,在`props`或者 `data`并没有该属性, 去看下 `v-bind`指令的使用
