### ISSUE TITLE
ToolBar不显示

### ISSUE THREAD

**Issue by JulyQuiet** [ElemeFE/vue-amap#79]
<template>
    <div id="demoComponent" class="demo-component">
        <el-amap vid="amap" :plugin="plugin">
        </el-amap>
    </div>
</template>

<script>
export default {
  data() {
    return {
      plugin: [{
        pName: 'ToolBar',
        events: {
          init(instance) {
            console.log(instance);
          }
        }
      }]
    };
  }
};
</script>
按实例写了toolbar，然而在页面并没不显示

**Comment by AxeMea** [comment]
@JulyQuiet 

你好，有初始化加载 `Toolbar` 插件吗？比如：

```javascript
AMap.initAMapApiLoader({
  // 高德的key
  key: 'YOUR_KEY',
  // 插件集合
  plugin: [ ... , 'ToolBar']
});
```

**Comment by jerry-i** [comment]
暂时所有插件都要提前声明，提前加载脚本
@JulyQuiet
