### ISSUE TITLE
如何引入AmapUI库

### ISSUE THREAD

**Issue by huncent** [ElemeFE/vue-amap#82]
请问怎么引入AmapUI库

**Comment by twocucao** [comment]
@huncent 虽然我觉得不太适合引入这个库.但同问.

我再补充一下,

AmapUI的Example在这里:

http://lbs.amap.com/api/javascript-api/example/amap-ui-basiccontrol/index

正常的情况在不用Vue的情况下,在引入AMap的组件后引入AMAPUI库只需要写
```html
    <script src="//webapi.amap.com/ui/1.0/main.js"></script>
```
VUEJS中没有使用Callback的的JS引入应该如何做呢,特别是这个文件还依赖动态引入的AMAP.

可以给一些思路吗?

**Comment by CrazyWisdom** [comment]
+1

**Comment by WangHui0306** [comment]
同问，拖拽定位等等功能，都依赖于AMapUI

**Comment by jerry-i** [comment]
已更新 https://elemefe.github.io/vue-amap/#/zh-cn/introduction/ui-component
