### ISSUE TITLE
中心点和折线坐标修改后地图不显示的问题

### ISSUE THREAD

**Issue by wtl1019** [ElemeFE/vue-amap#83]
按照说明文档折线示例，地图加载如预期，但是当修改了center和path的坐标后，地图不显示，修改的坐标如下：
     center: [39.916527,116.397128],
      path: [[39.930456,116.387554],
               [39.929008,116.414162],
               [39.909786,116.379314]]
请问这个是怎么回事呢？

**Comment by AxeMea** [comment]
@wtl1019 

你好，能直接贴上你的具体代码吗？

**Comment by wtl1019** [comment]
就是文档里覆盖物折线那部分代码，地图是可以显示的，但是我改成上面那部分的经纬度坐标后就不显示了

**Comment by wtl1019** [comment]
就是按文档里  覆盖物折线  那一块代码粘贴，是可以的，然后我只把上面贴的那几个坐标改了，想显示在北京，地图就不显示了，代码如下：
<template lang="html">
  <div id="demoComponent" class="demo-component" style="height:667px" ref="task">
      <el-amap vid="amap" :zoom="zoom" :center="center" :amapManager="amapManager">
        <el-amap-polyline :editable="polyline.editable"  :path="polyline.path" :events="polyline.events" :strokeColor="polyline.strokeColor"></el-amap-polyline>
      </el-amap>
      
  </div>
</template>

<script>
import { AMapManager } from 'vue-amap';
let amapManager = new AMapManager();
const POLYGON_ID = 'POLYGON_ID';
const lineColor = '#F44741';
export default {
  name: 'demoComponent',
  props: {
      task: {
        type: Object
      }
  },
  data() {
    return {
      zoom: 12,
      amapManager: amapManager,
      center:  [39.916527,116.397128],
      polyline: {
        vid: POLYGON_ID,
        path: [[39.930456,116.387554],
               [39.929008,116.414162],
               [39.909786,116.379314]],
        events: {
          click(e) {
            alert('click polyline');
          },
          end: (e) => {
            let newPath = e.target.getPath().map(point => [point.lng, point.lat]);
            console.log(newPath);
          }
        },
        editable: false,
        strokeColor: lineColor
      }
    };
  }
};
</script>

**Comment by wtl1019** [comment]
就是按文档里 覆盖物折线 那一块代码粘贴，是可以的，然后我只把上面贴的那几个坐标改了，想显示在北京，地图就不显示了，代码如下：
`<template lang="html">
  <div id="demoComponent" class="demo-component" style="height:667px" ref="task">
      <el-amap vid="amap" :zoom="zoom" :center="center" :amapManager="amapManager">
        <el-amap-polyline :editable="polyline.editable"  :path="polyline.path" :events="polyline.events" :strokeColor="polyline.strokeColor"></el-amap-polyline>
      </el-amap>
      
  </div>
</template>

<script>
import { AMapManager } from 'vue-amap';
let amapManager = new AMapManager();
const POLYGON_ID = 'POLYGON_ID';
const lineColor = '#F44741';
export default {
  name: 'demoComponent',
  props: {
      task: {
        type: Object
      }
  },
  data() {
    return {
      zoom: 12,
      amapManager: amapManager,
      center:  [39.916527,116.397128],
      polyline: {
        vid: POLYGON_ID,
        path: [[39.930456,116.387554],
               [39.929008,116.414162],
               [39.909786,116.379314]],
        events: {
          click(e) {
            alert('click polyline');
          },
          end: (e) => {
            let newPath = e.target.getPath().map(point => [point.lng, point.lat]);
            console.log(newPath);
          }
        },
        editable: false,
        strokeColor: lineColor
      }
    };
  }
};
</script>`

**Comment by wtl1019** [comment]
```<template lang="html">
  <div id="demoComponent" class="demo-component" style="height:667px">
      <el-amap vid="amap" :zoom="zoom" :center="center" :amapManager="amapManager">
        <el-amap-polyline :editable="polyline.editable"  :path="polyline.path" :events="polyline.events" :strokeColor="polyline.strokeColor"></el-amap-polyline>
      </el-amap>
      <!--<button type="button" name="button" v-on:click="changeEditable">change editable</button>-->
  </div>
</template>

<script>
import { AMapManager } from 'vue-amap';
let amapManager = new AMapManager();
const POLYGON_ID = 'POLYGON_ID';
const lineColor = '#F44741';
export default {
  name: 'demoComponent',
  props: {
      task: {
        type: Object
      }
  },
  data() {
    return {
      zoom: 12,
      amapManager: amapManager,
      center:  [39.916527,116.397128],
      polyline: {
        vid: POLYGON_ID,
        path: [[39.930456,116.387554],
               [39.929008,116.414162],
               [39.909786,116.379314]],
        events: {
          click(e) {
            alert('click polyline');
          },
          end: (e) => {
            let newPath = e.target.getPath().map(point => [point.lng, point.lat]);
            console.log(newPath);
          }
        },
        editable: false,
        strokeColor: lineColor
      }
    };
  }
};
</script>
'''

**Comment by wtl1019** [comment]
```
<template lang="html">
  <div id="demoComponent" class="demo-component" style="height:667px">
      <el-amap vid="amap" :zoom="zoom" :center="center" :amapManager="amapManager">
        <el-amap-polyline :editable="polyline.editable"  :path="polyline.path" :events="polyline.events" :strokeColor="polyline.strokeColor"></el-amap-polyline>
      </el-amap>
      <!--<button type="button" name="button" v-on:click="changeEditable">change editable</button>-->
  </div>
</template>

<script>
import { AMapManager } from 'vue-amap';
let amapManager = new AMapManager();
const POLYGON_ID = 'POLYGON_ID';
const lineColor = '#F44741';
export default {
  name: 'demoComponent',
  props: {
      task: {
        type: Object
      }
  },
  data() {
    return {
      zoom: 12,
      amapManager: amapManager,
      center:  [39.916527,116.397128],
      polyline: {
        vid: POLYGON_ID,
        path: [[39.930456,116.387554],
               [39.929008,116.414162],
               [39.909786,116.379314]],
        events: {
          click(e) {
            alert('click polyline');
          },
          end: (e) => {
            let newPath = e.target.getPath().map(point => [point.lng, point.lat]);
            console.log(newPath);
          }
        },
        editable: false,
        strokeColor: lineColor
      }
    };
  }
};
</script>
'''

**Comment by wtl1019** [comment]
您好，上面就是我的代码，中心点和path坐标按文档例子的话是可以显示的，改为上面的就不显示了

**Comment by wtl1019** [comment]
已解决，谢谢您
