### ISSUE TITLE
使用点坐标时，更换自定义的icon图标，没有效果

### ISSUE THREAD

**Issue by yizuiyitaoran** [ElemeFE/vue-amap#85]
关于点坐标的动态属性‘icon’-类型‘string’（高德地图的官方文档里的类型‘string/icon对象’）
我想自定义一个icon，但是没有效果呀
`markers: [
                    {
                        position: [121.59996, 31.197646],
                        events: {
                            click: () => {
                                alert('click marker');
                            },
                            dragend: (e) => {
                                this.markers[0].position = [e.lnglat.lng, e.lnglat.lat];
                            }
                        },
                        icon:"http://10.88.135.71:8010/res/images/qq.png",
                        draggable: true,
                        raiseOnDrag: true
                    }
                ]`
或
`markers: [
                    {
                        position: [121.59996, 31.197646],
                        events: {
                            click: () => {
                                alert('click marker');
                            },
                            dragend: (e) => {
                                this.markers[0].position = [e.lnglat.lng, e.lnglat.lat];
                            }
                        },
                        icon: new AMap.Icon({
                            size: new AMap.Size(40, 50),  //图标大小
                            image: "http://webapi.amap.com/theme/v1.3/images/newpc/way_btn2.png",
                            imageOffset: new AMap.Pixel(0, -60)
                        }),
                        draggable: true,
                        raiseOnDrag: true
                    }
                ]`

**Comment by AxeMea** [comment]
@yizuiyitaoran 

你好，是不是没有作如下的绑定。

```javascript
<marker v-for="marker in markers" :icon="marker.icon"></marker>
```

**Comment by yizuiyitaoran** [comment]
@AxeMea 哦，谢谢，我刚开始接触这些，对于文档不能举一反三的理解

**Comment by jjpassion** [comment]
icon 目前只支持string吗？
