### ISSUE TITLE
鼠标滑过marker显示信息窗体要怎么做？

### ISSUE THREAD

**Issue by rossroma** [ElemeFE/vue-amap#88]
业务需求： 地图上有若干marker，当鼠标移上时，需要显示一个信息窗体，来展示该marker的详细信息

请问要怎么实现？文档实在看不太明白

**Comment by jerry-i** [comment]
利用mouseover事件触发

**Comment by AxeMea** [comment]
@rossroma 

你好。

https://elemefe.github.io/vue-amap/#/zh-cn/examples/windows/info-window

这个 demo 是否能给你一些提示。
