### ISSUE TITLE
对maker设置title属性,鼠标划过maker没有提示

### ISSUE THREAD

**Issue by snecker** [ElemeFE/vue-amap#93]
```<el-amap-marker v-for="pos in orderPositions"
                           :key="pos.id"
                           :position="pos.position"
                           title="testTitle"
      ></el-amap-marker>
```
代码如上,只显示点,划过不显示title

**Comment by knight7890** [comment]
<el-amap-marker v-for="marker in markers" :position="marker.position" :events="marker.events" :visible="marker.visible" :draggable="marker.draggable" :icon = "marker.icon" :title = "marker.title"></el-amap-marker>
// 这里头部要设置一下 title
 markers: [
        {
          title:'hello how are you ?',

          position: [121.5273285, 31.21515044],}
 marker 里面也要设置下 title 就可以 ／／
