### ISSUE TITLE
Support English version

### ISSUE THREAD

**Issue by LeoEatle** [ElemeFE/vue-amap#95]
How can I change the language to English in vue-amap? I know I can do it in [Javascript API](http://lbs.amap.com/api/javascript-api/example/map/map-english/). But here I want a plugin or configuration for English.

**Comment by AxeMea** [comment]
@LeoEatle 

Hi ，你好。后面会放出这个语言属性，目前版本可以如此支持。

```
<el-amap vid="demo" events="events"></el-amap>

export default {
  data() {
    return {
      events: {
        init(o) {
          o.setLang('en');
        }
      }
    };
  }
};
```

**Comment by LeoEatle** [comment]
@AxeMea 
Thank you for your quick responding. But it does not work.
I get type error: `TypeError: o.setLang is not a function`.
This is the value of parameter o:
![image](https://cloud.githubusercontent.com/assets/14247110/25692458/581b940e-30d5-11e7-842c-e728aaf1c59a.png)
Is it caused by the plugins I use?

**Comment by LeoEatle** [comment]
@AxeMea Thank you for your quick responding. It works.

**Comment by AxeMea** [comment]
@LeoEatle 

OK, If problem is solved, close the issue pls. Thx.

**Comment by thearabbit** [comment]
👍

**Comment by emilianocds** [comment]
How it should the config on AMap v2.0? I tested and its not working:
 ```
var map = new AMap.Map('container', {
      center: [121.498586, 31.239637],
      lang: "en"
    });
```
https://lbs.amap.com/demo/javascript-api/example/map/map-english/
