### ISSUE TITLE
SearchBox 如何配置搜索国外的地址？

### ISSUE THREAD

**Issue by zaxlct** [ElemeFE/vue-amap#99]
您好，非常感谢您的项目。
我想请教怎么在 SearchBox 搜索国外的地址呢？
我在文档里给出的例子里输入国外的地址，但地图给出的响应都是国内。

**Comment by AxeMea** [comment]
@zaxlct 

你好，高德地图目前应该只支持国内地图吧。

**Comment by zaxlct** [comment]
@AxeMea 好的，我还真不知道。谢谢。
